<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.24">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>9&nbsp; Generalized additive mixed models – statmodels7</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<link href="../chapters/10-penalized.html" rel="next">
<link href="../chapters/08-glmm.html" rel="prev">
<script src="../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../site_libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-e986b704c747e817427b29ebc19a759e.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-a2ce0b05719297c8ab99eac5b5b92eaa.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<style>html{ scroll-behavior: smooth; }</style>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-sidebar floating quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../chapters/01-model.html">Using statmod()</a></li><li class="breadcrumb-item"><a href="../chapters/09-gamm.html"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Generalized additive mixed models</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header sidebar-header-stacked">
      <a href="../index.html" class="sidebar-logo-link">
      </a>
    <div class="sidebar-title mb-0 py-0">
      <a href="../">statmodels7</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Preface</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true">
 <span class="menu-text">Using statmod()</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/01-model.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">A first model</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/02-beyond.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Beyond the basics</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/03-lm.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Linear models and beyond</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/04-glm.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Generalized linear models</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/05-distributions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Distributions</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/06-gam.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Generalized additive models</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/07-lmm.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Linear mixed models</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/08-glmm.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Generalized linear mixed models</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/09-gamm.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Generalized additive mixed models</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true">
 <span class="menu-text">Special model terms</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/10-penalized.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Penalized regression</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/11-breakpoints.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Break-points</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/12-nonlinear.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Nonlinear models</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/13-timeseries.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Time series</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true">
 <span class="menu-text">Choosing</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/14-choosing.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Choosing</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true">
 <span class="menu-text">Extending the toolkit</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/15-own-distributions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">Writing a distribution and a link</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/16-own-terms.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">16</span>&nbsp; <span class="chapter-title">Writing a model term</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/A2-references.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">References</span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active" data-toc-expanded="99">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#sec-gamm-intercept" id="toc-sec-gamm-intercept" class="nav-link active" data-scroll-target="#sec-gamm-intercept"><span class="header-section-number">9.1</span> A smooth and a random intercept</a>
  <ul>
  <li><a href="#a-random-slope" id="toc-a-random-slope" class="nav-link" data-scroll-target="#a-random-slope">A random slope</a></li>
  <li><a href="#sec-gamm-band" id="toc-sec-gamm-band" class="nav-link" data-scroll-target="#sec-gamm-band">The band of the typical curve</a></li>
  </ul></li>
  <li><a href="#sec-gamm-by" id="toc-sec-gamm-by" class="nav-link" data-scroll-target="#sec-gamm-by"><span class="header-section-number">9.2</span> A smooth for each group</a>
  <ul>
  <li><a href="#sec-gamm-chick" id="toc-sec-gamm-chick" class="nav-link" data-scroll-target="#sec-gamm-chick">A curve for each chick</a></li>
  </ul></li>
  <li><a href="#sec-gamm-sigma" id="toc-sec-gamm-sigma" class="nav-link" data-scroll-target="#sec-gamm-sigma"><span class="header-section-number">9.3</span> Smooths and random effects in sigma</a></li>
  <li><a href="#sec-gamm-counts" id="toc-sec-gamm-counts" class="nav-link" data-scroll-target="#sec-gamm-counts"><span class="header-section-number">9.4</span> A model for counts</a>
  <ul>
  <li><a href="#random-effects-on-the-dispersion" id="toc-random-effects-on-the-dispersion" class="nav-link" data-scroll-target="#random-effects-on-the-dispersion">Random effects on the dispersion</a></li>
  </ul></li>
  <li><a href="#sec-gamm-id" id="toc-sec-gamm-id" class="nav-link" data-scroll-target="#sec-gamm-id"><span class="header-section-number">9.5</span> Shared smoothing parameters</a>
  <ul>
  <li><a href="#lagged-covariates" id="toc-lagged-covariates" class="nav-link" data-scroll-target="#lagged-covariates">Lagged covariates</a></li>
  <li><a href="#levels-that-share-a-parameter" id="toc-levels-that-share-a-parameter" class="nav-link" data-scroll-target="#levels-that-share-a-parameter">Levels that share a parameter</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../chapters/01-model.html">Using statmod()</a></li><li class="breadcrumb-item"><a href="../chapters/09-gamm.html"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Generalized additive mixed models</span></a></li></ol></nav>
<div class="quarto-title">
<h1 class="title"><span id="sec-gamm" class="quarto-section-identifier"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Generalized additive mixed models</span></span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<p>A generalized additive mixed model has smooth functions and random effects in the same predictor <span class="citation" data-cites="lin1999 ruppert2003">(<a href="A2-references.html#ref-lin1999" role="doc-biblioref">Lin and Zhang 1999</a>; <a href="A2-references.html#ref-ruppert2003" role="doc-biblioref">Ruppert, Wand, and Carroll 2003</a>)</span>: <span class="math display">\[
\eta_{ij} = x_{ij}^\top\beta + \sum_k f_k(t_{ij}) + z_{ij}^\top b_i ,
\]</span> where <span class="math inline">\(i\)</span> is the group and <span class="math inline">\(j\)</span> the observation. In <code>statmodels7</code> the two kinds of term are built in the same way. The coefficients of a smooth have the penalty <span class="math inline">\(\lambda\,\beta^\top S\beta\)</span> of <a href="06-gam.html" class="quarto-xref"><span>Chapter 6</span></a>, and the random effects have the penalty <span class="math inline">\(b^\top\Sigma_b^{-1}b\)</span> of <a href="07-lmm.html" class="quarto-xref"><span>Chapter 7</span></a>. Both penalties are minus the logarithm of a gaussian density, so the REML criterion of the previous chapters integrates both kinds of coefficient and estimates <span class="math inline">\(\lambda\)</span> and <span class="math inline">\(\Sigma_b\)</span> together. Nothing new is needed to fit the model: a formula with <code>s()</code> and <code>random()</code> is enough.</p>
<p>Two other packages fit these models, and they meet the same idea from the two opposite sides. The package <code>mgcv</code> writes a random intercept as a smooth whose penalty is the identity matrix (<code>bs = "re"</code>) <span class="citation" data-cites="wood2017">(<a href="A2-references.html#ref-wood2017" role="doc-biblioref">Wood 2017</a>)</span>. The package <code>glmmTMB</code> writes a smooth as a random effect: the part of the smooth that the penalty shrinks becomes a vector of random effects with a common variance, and the part that the penalty leaves free becomes a fixed effect <span class="citation" data-cites="brooks2017">(<a href="A2-references.html#ref-brooks2017" role="doc-biblioref">Brooks et al. 2017</a>)</span>. We compare with both throughout the chapter. As in <a href="06-gam.html" class="quarto-xref"><span>Chapter 6</span></a> we call <code>mgcv</code> as <code>mgcv::gam()</code> without attaching it.</p>
<section id="sec-gamm-intercept" class="level2" data-number="9.1">
<h2 data-number="9.1" class="anchored" data-anchor-id="sec-gamm-intercept"><span class="header-section-number">9.1</span> A smooth and a random intercept</h2>
<p>The data frame <code>ChickWeight</code> of <a href="06-gam.html#sec-gam-by" class="quarto-xref"><span>Section 6.4</span></a> gives the weight, in grams, of 50 chicks from birth to day 21 <span class="citation" data-cites="crowder1990">(<a href="A2-references.html#ref-crowder1990" role="doc-biblioref">Crowder and Hand 1990</a>)</span>. There we fitted one smooth curve of time for each diet and ignored that the observations of one chick are correlated. We now give each chick a random intercept and start with one curve for all the chicks: <span class="math display">\[
\mu_{ij} = \beta_0 + f(t_{ij}) + b_i, \qquad b_i \sim \mathrm{N}(0, \tau).
\]</span></p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>ChickWeight<span class="sc">$</span>Diet <span class="ot">&lt;-</span> <span class="fu">factor</span>(ChickWeight<span class="sc">$</span>Diet, <span class="at">ordered =</span> <span class="cn">FALSE</span>)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>fit_ri <span class="ot">&lt;-</span> <span class="fu">statmod</span>(weight <span class="sc">~</span> <span class="fu">s</span>(Time, <span class="fu">bspline_smooth</span>(<span class="at">k =</span> <span class="dv">8</span>)) <span class="sc">+</span> <span class="fu">random</span>(<span class="sc">~</span> <span class="dv">1</span> <span class="sc">|</span> Chick),</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>                  <span class="at">distrib =</span> <span class="fu">gaussian1_distrib</span>(), <span class="at">data =</span> ChickWeight)</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(fit_ri)</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; A statmod fit</span></span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; </span></span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; Call:  statmod(formula = weight ~ s(Time, bspline_smooth(k = 8)) + random(~1 | </span></span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;             Chick), distrib = gaussian1_distrib(), data = ChickWeight)</span></span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; </span></span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; Distribution: gaussian1     Observations: 578</span></span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; </span></span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; === mu   [identity link]</span></span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; </span></span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; Parametric terms</span></span>
<span id="cb1-15"><a href="#cb1-15" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;                estimate    se     z       p lower upper</span></span>
<span id="cb1-16"><a href="#cb1-16" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;   (Intercept)     121.3 3.968 30.57 &lt; 1e-16 113.5 129.1</span></span>
<span id="cb1-17"><a href="#cb1-17" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; </span></span>
<span id="cb1-18"><a href="#cb1-18" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; s(Time, bspline_smooth(k = 8))   [7 coefficients, edf 3.10]</span></span>
<span id="cb1-19"><a href="#cb1-19" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;                  estimate    se     z       p    lower  upper</span></span>
<span id="cb1-20"><a href="#cb1-20" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;   lambda [reml]    0.0416 0.041               0.006027 0.2871</span></span>
<span id="cb1-21"><a href="#cb1-21" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;   lin               58.97 1.158 50.93 &lt; 1e-16     56.7  61.24</span></span>
<span id="cb1-22"><a href="#cb1-22" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; </span></span>
<span id="cb1-23"><a href="#cb1-23" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; random(~1 | Chick)   [50 coefficients, edf 44.64]</span></span>
<span id="cb1-24"><a href="#cb1-24" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;                 estimate    se lower upper</span></span>
<span id="cb1-25"><a href="#cb1-25" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;   sigma [reml]     26.78 2.955 21.58 33.25</span></span>
<span id="cb1-26"><a href="#cb1-26" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;   predicted effects (50 levels of Chick)</span></span>
<span id="cb1-27"><a href="#cb1-27" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;                    Min. 1st Qu. Median Mean 3rd Qu.  Max.</span></span>
<span id="cb1-28"><a href="#cb1-28" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;     (Intercept)  -52.22  -17.83 0.2718    0   17.56 64.38</span></span>
<span id="cb1-29"><a href="#cb1-29" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; </span></span>
<span id="cb1-30"><a href="#cb1-30" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; === sigma   [log link]</span></span>
<span id="cb1-31"><a href="#cb1-31" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; </span></span>
<span id="cb1-32"><a href="#cb1-32" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; Parametric terms</span></span>
<span id="cb1-33"><a href="#cb1-33" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;                estimate      se     z       p lower upper</span></span>
<span id="cb1-34"><a href="#cb1-34" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;   (Intercept)     3.318 0.03084 107.6 &lt; 1e-16 3.257 3.378</span></span>
<span id="cb1-35"><a href="#cb1-35" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; </span></span>
<span id="cb1-36"><a href="#cb1-36" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 95% intervals, bayesian variance</span></span>
<span id="cb1-37"><a href="#cb1-37" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; conditional log-likelihood -2713.454173    effective df 49.74</span></span>
<span id="cb1-38"><a href="#cb1-38" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; cAIC 5526.391    cBIC 5743.242</span></span>
<span id="cb1-39"><a href="#cb1-39" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; fitted in 2.47 s</span></span>
<span id="cb1-40"><a href="#cb1-40" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; inner   max |grad|/se 7.1e-15   min eigen 0.043</span></span>
<span id="cb1-41"><a href="#cb1-41" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; outer   max |grad|/se 3.5e-10   min eigen 0.98</span></span>
<span id="cb1-42"><a href="#cb1-42" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 1 note: print(summary(fit), notes = TRUE)</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>The summary has a block for the smooth and a block for the random intercept. The smooth spends 3.10 effective degrees of freedom out of its 7 coefficients. The standard deviation of the chicks’ intercepts is <span class="math inline">\(\hat\tau = 26.78\)</span> grams, about as large as the residual standard deviation <span class="math inline">\(\hat\sigma = 27.60\)</span> grams.</p>
<p>In <code>mgcv</code> the random intercept is the smooth <code>s(Chick, bs = "re")</code>. Its penalty is <span class="math inline">\(\lambda_b\, b^\top b\)</span>, divided by the residual variance, so the standard deviation of the random effects is <span class="math inline">\(\sigma/\sqrt{\lambda_b}\)</span>:</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>g_ri <span class="ot">&lt;-</span> mgcv<span class="sc">::</span><span class="fu">gam</span>(weight <span class="sc">~</span> <span class="fu">s</span>(Time, <span class="at">bs =</span> <span class="st">"bs"</span>, <span class="at">k =</span> <span class="dv">8</span>) <span class="sc">+</span> <span class="fu">s</span>(Chick, <span class="at">bs =</span> <span class="st">"re"</span>),</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>                  <span class="at">data =</span> ChickWeight, <span class="at">method =</span> <span class="st">"REML"</span>)</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a><span class="fu">c</span>(<span class="at">statmod =</span> <span class="fu">hyper</span>(fit_ri)<span class="sc">$</span>estimate[<span class="dv">2</span>],</span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">mgcv =</span> <span class="fu">sqrt</span>(g_ri<span class="sc">$</span>sig2 <span class="sc">/</span> g_ri<span class="sc">$</span>sp[<span class="dv">2</span>]))</span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;       statmod mgcv.s(Chick) </span></span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;      26.78313      26.78313</span></span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a><span class="fu">max</span>(<span class="fu">abs</span>(<span class="fu">fitted</span>(fit_ri) <span class="sc">-</span> <span class="fu">fitted</span>(g_ri)))</span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; [1] 1.543418e-08</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>The two packages give the same standard deviation and the same fitted values.</p>
<section id="a-random-slope" class="level3">
<h3 class="anchored" data-anchor-id="a-random-slope">A random slope</h3>
<p>The chicks grow at different rates, so their weights spread out with time. A random slope on time describes this: <span class="math display">\[
\mu_{ij} = \beta_0 + f(t_{ij}) + b_{0i} + b_{1i} t_{ij}, \qquad
(b_{0i}, b_{1i})^\top \sim \mathrm{N}(0, \Sigma_b).
\]</span></p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>fit_rs <span class="ot">&lt;-</span> <span class="fu">statmod</span>(weight <span class="sc">~</span> <span class="fu">s</span>(Time, <span class="fu">bspline_smooth</span>(<span class="at">k =</span> <span class="dv">8</span>)) <span class="sc">+</span> <span class="fu">random</span>(<span class="sc">~</span> Time <span class="sc">|</span> Chick),</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>                  <span class="at">distrib =</span> <span class="fu">gaussian1_distrib</span>(), <span class="at">data =</span> ChickWeight)</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(fit_rs)</span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; A statmod fit</span></span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; </span></span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; Call:  statmod(formula = weight ~ s(Time, bspline_smooth(k = 8)) + random(~Time | </span></span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;             Chick), distrib = gaussian1_distrib(), data = ChickWeight)</span></span>
<span id="cb3-8"><a href="#cb3-8" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; </span></span>
<span id="cb3-9"><a href="#cb3-9" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; Distribution: gaussian1     Observations: 578</span></span>
<span id="cb3-10"><a href="#cb3-10" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; </span></span>
<span id="cb3-11"><a href="#cb3-11" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; === mu   [identity link]</span></span>
<span id="cb3-12"><a href="#cb3-12" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; </span></span>
<span id="cb3-13"><a href="#cb3-13" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; Parametric terms</span></span>
<span id="cb3-14"><a href="#cb3-14" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;                estimate    se     z       p lower upper</span></span>
<span id="cb3-15"><a href="#cb3-15" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;   (Intercept)     120.2 4.136 29.06 &lt; 1e-16 112.1 128.3</span></span>
<span id="cb3-16"><a href="#cb3-16" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; </span></span>
<span id="cb3-17"><a href="#cb3-17" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; s(Time, bspline_smooth(k = 8))   [7 coefficients, edf 4.41]</span></span>
<span id="cb3-18"><a href="#cb3-18" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;                  estimate      se     z       p   lower  upper</span></span>
<span id="cb3-19"><a href="#cb3-19" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;   lambda [reml]   0.03795 0.03287               0.00695 0.2072</span></span>
<span id="cb3-20"><a href="#cb3-20" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;   lin               57.55   3.582 16.07 &lt; 1e-16   50.53  64.57</span></span>
<span id="cb3-21"><a href="#cb3-21" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; </span></span>
<span id="cb3-22"><a href="#cb3-22" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; random(~Time | Chick)   [100 coefficients, edf 69.74]</span></span>
<span id="cb3-23"><a href="#cb3-23" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;                                  estimate      se lower   upper</span></span>
<span id="cb3-24"><a href="#cb3-24" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;   sd[(Intercept)] [reml]            12.02   1.551 9.329   15.48</span></span>
<span id="cb3-25"><a href="#cb3-25" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;   sd[Time] [reml]                   3.693  0.3826 3.014   4.525</span></span>
<span id="cb3-26"><a href="#cb3-26" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;   cor[(Intercept), Time] [reml]    -0.924 0.03556 -0.97 -0.8141</span></span>
<span id="cb3-27"><a href="#cb3-27" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;   predicted effects (50 levels of Chick)</span></span>
<span id="cb3-28"><a href="#cb3-28" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;                    Min. 1st Qu.  Median Mean 3rd Qu.  Max.</span></span>
<span id="cb3-29"><a href="#cb3-29" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;     (Intercept)  -24.64  -7.841 -0.8384    0   8.463 22.09</span></span>
<span id="cb3-30"><a href="#cb3-30" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;     Time         -7.152  -2.444 0.02372    0   2.525  8.71</span></span>
<span id="cb3-31"><a href="#cb3-31" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; </span></span>
<span id="cb3-32"><a href="#cb3-32" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; === sigma   [log link]</span></span>
<span id="cb3-33"><a href="#cb3-33" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; </span></span>
<span id="cb3-34"><a href="#cb3-34" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; Parametric terms</span></span>
<span id="cb3-35"><a href="#cb3-35" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;                estimate      se     z       p lower upper</span></span>
<span id="cb3-36"><a href="#cb3-36" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;   (Intercept)     2.433 0.03195 76.14 &lt; 1e-16  2.37 2.495</span></span>
<span id="cb3-37"><a href="#cb3-37" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; </span></span>
<span id="cb3-38"><a href="#cb3-38" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 95% intervals, bayesian variance</span></span>
<span id="cb3-39"><a href="#cb3-39" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; conditional log-likelihood -2188.728821    effective df 76.15</span></span>
<span id="cb3-40"><a href="#cb3-40" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; cAIC 4529.758    cBIC 4861.741</span></span>
<span id="cb3-41"><a href="#cb3-41" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; fitted in 4.04 s</span></span>
<span id="cb3-42"><a href="#cb3-42" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; inner   max |grad|/se 1.1e-14   min eigen 0.0029</span></span>
<span id="cb3-43"><a href="#cb3-43" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; outer   max |grad|/se 2.7e-07   min eigen 0.25</span></span>
<span id="cb3-44"><a href="#cb3-44" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 1 note: print(summary(fit), notes = TRUE)</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>The two models have the same fixed effects, so their restricted log-likelihoods can be compared. Under the smaller model the variance of the slopes is zero, on the boundary of its range, so the likelihood ratio has the distribution <span class="math inline">\(\tfrac12\chi^2_1 + \tfrac12\chi^2_2\)</span> and not <span class="math inline">\(\chi^2_2\)</span> <span class="citation" data-cites="self1987">(<a href="A2-references.html#ref-self1987" role="doc-biblioref">Self and Liang 1987</a>)</span>:</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>l_ri <span class="ot">&lt;-</span> <span class="fu">as.numeric</span>(<span class="fu">logLik</span>(fit_ri, <span class="at">type =</span> <span class="st">"marginal"</span>))</span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>l_rs <span class="ot">&lt;-</span> <span class="fu">as.numeric</span>(<span class="fu">logLik</span>(fit_rs, <span class="at">type =</span> <span class="st">"marginal"</span>))</span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a>lr_rs <span class="ot">&lt;-</span> <span class="dv">2</span> <span class="sc">*</span> (l_rs <span class="sc">-</span> l_ri)</span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a>lr_rs</span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; [1] 872.7899</span></span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a><span class="fl">0.5</span> <span class="sc">*</span> <span class="fu">pchisq</span>(lr_rs, <span class="at">df =</span> <span class="dv">1</span>, <span class="at">lower.tail =</span> <span class="cn">FALSE</span>) <span class="sc">+</span></span>
<span id="cb4-7"><a href="#cb4-7" aria-hidden="true" tabindex="-1"></a>  <span class="fl">0.5</span> <span class="sc">*</span> <span class="fu">pchisq</span>(lr_rs, <span class="at">df =</span> <span class="dv">2</span>, <span class="at">lower.tail =</span> <span class="cn">FALSE</span>)</span>
<span id="cb4-8"><a href="#cb4-8" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; [1] 1.536804e-190</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>The random slope is needed. The correlation between the intercepts and the slopes is strongly negative. The deviation of a chick from the typical curve is <span class="math inline">\(b_{0i} + b_{1i}t\)</span>, and its variance <span class="math inline">\(\Sigma_{11} + 2t\,\Sigma_{12} + t^2\Sigma_{22}\)</span> is smallest at <span class="math inline">\(t = -\Sigma_{12}/\Sigma_{22}\)</span>. As in <a href="07-lmm.html#sec-lmm-slope" class="quarto-xref"><span>Section 7.2</span></a>, <code>param_value()</code> turns the hyperparameters of the random slope into <span class="math inline">\(\Sigma_b\)</span>:</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>h_rs <span class="ot">&lt;-</span> <span class="fu">hyper</span>(fit_rs)</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>S_rs <span class="ot">&lt;-</span> <span class="fu">param_value</span>(<span class="fu">log_cholesky</span>(<span class="dv">2</span>), <span class="at">eta =</span> h_rs<span class="sc">$</span>estimate[h_rs<span class="sc">$</span>name <span class="sc">!=</span> <span class="st">"lambda"</span>])</span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>S_rs</span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;           v1        v2</span></span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; v1 144.37584 -41.00005</span></span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; v2 -41.00005  13.63835</span></span>
<span id="cb5-7"><a href="#cb5-7" aria-hidden="true" tabindex="-1"></a>t_min <span class="ot">&lt;-</span> <span class="sc">-</span>S_rs[<span class="dv">1</span>, <span class="dv">2</span>] <span class="sc">/</span> S_rs[<span class="dv">2</span>, <span class="dv">2</span>]</span>
<span id="cb5-8"><a href="#cb5-8" aria-hidden="true" tabindex="-1"></a>t_min</span>
<span id="cb5-9"><a href="#cb5-9" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; [1] 3.006233</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>The correlation is -0.924, and the chicks are closest to each other 3.0 days after birth and spread out afterwards.</p>
<p><code>glmmTMB()</code> accepts a smooth in its formula and gives the same estimates:</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>tmb_rs <span class="ot">&lt;-</span> glmmTMB<span class="sc">::</span><span class="fu">glmmTMB</span>(weight <span class="sc">~</span> <span class="fu">s</span>(Time, <span class="at">bs =</span> <span class="st">"bs"</span>, <span class="at">k =</span> <span class="dv">8</span>) <span class="sc">+</span> (Time <span class="sc">|</span> Chick),</span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>                           <span class="at">data =</span> ChickWeight, <span class="at">REML =</span> <span class="cn">TRUE</span>)</span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a>glmmTMB<span class="sc">::</span><span class="fu">VarCorr</span>(tmb_rs)</span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; </span></span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; Conditional model:</span></span>
<span id="cb6-6"><a href="#cb6-6" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  Groups   Name        Std.Dev. Corr   </span></span>
<span id="cb6-7"><a href="#cb6-7" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  dummy    dummy1       3.3873         </span></span>
<span id="cb6-8"><a href="#cb6-8" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  Chick    (Intercept) 12.0156         </span></span>
<span id="cb6-9"><a href="#cb6-9" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;           Time         3.6930  -0.924 </span></span>
<span id="cb6-10"><a href="#cb6-10" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  Residual             11.3907</span></span>
<span id="cb6-11"><a href="#cb6-11" aria-hidden="true" tabindex="-1"></a><span class="fu">logLik</span>(tmb_rs)</span>
<span id="cb6-12"><a href="#cb6-12" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 'log Lik.' -2359.369 (df=7)</span></span>
<span id="cb6-13"><a href="#cb6-13" aria-hidden="true" tabindex="-1"></a><span class="fu">logLik</span>(fit_rs, <span class="at">type =</span> <span class="st">"marginal"</span>)</span>
<span id="cb6-14"><a href="#cb6-14" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 'log Lik.' -2360.764 (df=6)</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>The group <code>dummy</code> of <code>glmmTMB</code> is the smooth: its standard deviation measures how much the wiggly part of the curve is shrunk, and it plays the role of <span class="math inline">\(\lambda\)</span>. The two restricted log-likelihoods differ by a constant. REML integrates every coefficient without a penalty with a flat prior, and the integral depends on the scale of the columns of these coefficients: if a column is multiplied by <span class="math inline">\(a\)</span>, its coefficient is divided by <span class="math inline">\(a\)</span> and the integral changes by <span class="math inline">\(\log\lvert a\rvert\)</span>. The free part of the smooth is a straight line in time, and the two packages scale its column differently:</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>x_sm <span class="ot">&lt;-</span> <span class="fu">model.matrix</span>(fit_rs)[, <span class="st">"s(Time).lin"</span>]</span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>x_tmb <span class="ot">&lt;-</span> glmmTMB<span class="sc">::</span><span class="fu">getME</span>(tmb_rs, <span class="st">"X"</span>)[, <span class="st">"s(Time)1"</span>]</span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a>a_lin <span class="ot">&lt;-</span> <span class="fu">coef</span>(<span class="fu">lm</span>(x_sm <span class="sc">~</span> x_tmb))[[<span class="st">"x_tmb"</span>]]</span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a><span class="fu">log</span>(<span class="fu">abs</span>(a_lin))</span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; [1] 1.395387</span></span>
<span id="cb7-6"><a href="#cb7-6" aria-hidden="true" tabindex="-1"></a><span class="fu">as.numeric</span>(<span class="fu">logLik</span>(tmb_rs)) <span class="sc">-</span> l_rs</span>
<span id="cb7-7"><a href="#cb7-7" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; [1] 1.395387</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>The constant is the same for every model with this smooth, so a difference between two restricted log-likelihoods, like the likelihood ratio above, is the same in both packages.</p>
<p><a href="#fig-chicks" class="quarto-xref">Figure&nbsp;<span>9.1</span></a> shows the curve of a typical chick, with <span class="math inline">\(b_i = 0\)</span>, and the curves of five chicks.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-chicks" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-chicks-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="09-gamm_files/figure-html/fig-chicks-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:100.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-chicks-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;9.1: Weight against time for five chicks, with each chick’s fitted curve and the curve of a typical chick (random intercept and slope).
</figcaption>
</figure>
</div>
</div>
</div>
</section>
<section id="sec-gamm-band" class="level3">
<h3 class="anchored" data-anchor-id="sec-gamm-band">The band of the typical curve</h3>
<p>The curve of a typical chick is an estimate, and <code>predict()</code> with <code>se = TRUE</code> gives it a pointwise 95% band. The band depends on the variance matrix of <a href="02-beyond.html#sec-beyond-variances" class="quarto-xref"><span>Section 2.1</span></a>. In a model with random effects the three matrices answer three different questions. The matrix <span class="math inline">\(V_f\)</span> treats the effects <span class="math inline">\(b_i\)</span> of the 50 chicks as fixed numbers, so it measures how much the curve would change if we weighed the same 50 chicks again. The matrix <span class="math inline">\(V_b\)</span> treats the <span class="math inline">\(b_i\)</span> as draws from their gaussian distribution, so it measures how well a sample of 50 chicks determines the curve of the population of chicks. The matrix <span class="math inline">\(V_u\)</span> adds to <span class="math inline">\(V_b\)</span> the uncertainty of <span class="math inline">\(\lambda\)</span> and of <span class="math inline">\(\Sigma_b\)</span>. We compute the three bands at days 0, 10.5 and 21:</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>tg <span class="ot">&lt;-</span> <span class="fu">seq</span>(<span class="at">from =</span> <span class="dv">0</span>, <span class="at">to =</span> <span class="dv">21</span>, <span class="at">length.out =</span> <span class="dv">101</span>)</span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>nd_t <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">Time =</span> tg, <span class="at">Chick =</span> <span class="fu">factor</span>(<span class="st">"1"</span>, <span class="at">levels =</span> <span class="fu">levels</span>(ChickWeight<span class="sc">$</span>Chick)))</span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a>types <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"bayesian"</span>, <span class="st">"frequentist"</span>, <span class="st">"unconditional"</span>)</span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a>bands <span class="ot">&lt;-</span> <span class="fu">lapply</span>(types, <span class="cf">function</span>(ty) {</span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">predict</span>(fit_rs, <span class="at">what =</span> <span class="st">"mu"</span>, <span class="at">newdata =</span> nd_t, <span class="at">random =</span> <span class="st">"zero"</span>, <span class="at">se =</span> <span class="cn">TRUE</span>,</span>
<span id="cb8-6"><a href="#cb8-6" aria-hidden="true" tabindex="-1"></a>          <span class="at">type =</span> ty)</span>
<span id="cb8-7"><a href="#cb8-7" aria-hidden="true" tabindex="-1"></a>})</span>
<span id="cb8-8"><a href="#cb8-8" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(bands) <span class="ot">&lt;-</span> types</span>
<span id="cb8-9"><a href="#cb8-9" aria-hidden="true" tabindex="-1"></a><span class="fu">sapply</span>(bands, <span class="cf">function</span>(p) p<span class="sc">$</span>se[<span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">51</span>, <span class="dv">101</span>)])</span>
<span id="cb8-10"><a href="#cb8-10" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;      bayesian frequentist unconditional</span></span>
<span id="cb8-11"><a href="#cb8-11" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; [1,] 2.242387   1.4046583      2.292312</span></span>
<span id="cb8-12"><a href="#cb8-12" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; [2,] 4.103402   0.9260652      4.106455</span></span>
<span id="cb8-13"><a href="#cb8-13" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; [3,] 9.585735   1.4997067      9.587510</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>The frequentist standard errors stay between 0.9 and 1.5 grams at every age. The Bayesian ones grow with age, from 2.2 grams at birth to 9.6 grams at day 21. The growth comes from the random slopes: the chicks spread out with age, so the average curve of 50 chicks is less certain at day 21 than at birth. The variance of the deviation <span class="math inline">\(b_{0i} + b_{1i}t\)</span> of one chick is <span class="math inline">\((1, t)\,\Sigma_b\,(1, t)^\top\)</span>, and the mean of 50 such deviations has a standard deviation of <span class="math inline">\(\sqrt{(1, t)\,\Sigma_b\,(1, t)^\top / 50}\)</span>:</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>sd_mean <span class="ot">&lt;-</span> <span class="cf">function</span>(t) <span class="fu">sqrt</span>(<span class="fu">drop</span>(<span class="fu">c</span>(<span class="dv">1</span>, t) <span class="sc">%*%</span> S_rs <span class="sc">%*%</span> <span class="fu">c</span>(<span class="dv">1</span>, t)) <span class="sc">/</span> <span class="dv">50</span>)</span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a><span class="fu">rbind</span>(<span class="at">bayesian =</span> bands<span class="sc">$</span>bayesian<span class="sc">$</span>se[<span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">51</span>, <span class="dv">101</span>)],</span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>      <span class="at">chicks =</span> <span class="fu">sapply</span>(<span class="fu">c</span>(<span class="dv">0</span>, <span class="fl">10.5</span>, <span class="dv">21</span>), sd_mean))</span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;              [,1]     [,2]     [,3]</span></span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; bayesian 2.242387 4.103402 9.585735</span></span>
<span id="cb9-6"><a href="#cb9-6" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; chicks   1.699269 3.967374 9.420069</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>From the first week on, most of the Bayesian standard error is the variation among chicks. The frequentist band leaves this variation out, so it is the right band only for a statement about these 50 chicks. For a statement about chicks in general, which is what a curve of a typical chick is for, the Bayesian band is the right one. The unconditional band is wider than the Bayesian band by at most 5.1 per cent: the 50 chicks determine <span class="math inline">\(\lambda\)</span> and <span class="math inline">\(\Sigma_b\)</span> well enough that their uncertainty adds little. <a href="#fig-band" class="quarto-xref">Figure&nbsp;<span>9.2</span></a> shows the three bands.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-band" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-band-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="09-gamm_files/figure-html/fig-band-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:100.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-band-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;9.2: Top: the curve of a typical chick with the 95% band from the Bayesian variance (shaded) and from the frequentist variance (dashed). Bottom: the standard error of the curve under the three variance matrices.
</figcaption>
</figure>
</div>
</div>
</div>
<p>In <code>mgcv</code> the matrices <span class="math inline">\(V_b\)</span> and <span class="math inline">\(V_f\)</span> are the components <code>Vp</code> and <code>Ve</code> of a fit. On the model with a random intercept the typical curve, which leaves out the term <code>s(Chick)</code>, has the same two bands in the two packages:</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>Xg <span class="ot">&lt;-</span> <span class="fu">predict</span>(g_ri, <span class="at">newdata =</span> nd_t, <span class="at">type =</span> <span class="st">"lpmatrix"</span>)</span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>Xg[, <span class="fu">grepl</span>(<span class="st">"Chick"</span>, <span class="fu">colnames</span>(Xg))] <span class="ot">&lt;-</span> <span class="dv">0</span></span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a>se_mgcv <span class="ot">&lt;-</span> <span class="cf">function</span>(V) <span class="fu">sqrt</span>(<span class="fu">rowSums</span>((Xg <span class="sc">%*%</span> V) <span class="sc">*</span> Xg))</span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a>se_sm <span class="ot">&lt;-</span> <span class="cf">function</span>(ty) {</span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">predict</span>(fit_ri, <span class="at">what =</span> <span class="st">"mu"</span>, <span class="at">newdata =</span> nd_t, <span class="at">random =</span> <span class="st">"zero"</span>, <span class="at">se =</span> <span class="cn">TRUE</span>,</span>
<span id="cb10-6"><a href="#cb10-6" aria-hidden="true" tabindex="-1"></a>          <span class="at">type =</span> ty)<span class="sc">$</span>se</span>
<span id="cb10-7"><a href="#cb10-7" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb10-8"><a href="#cb10-8" aria-hidden="true" tabindex="-1"></a><span class="fu">c</span>(<span class="at">bayesian =</span> <span class="fu">max</span>(<span class="fu">abs</span>(<span class="fu">se_sm</span>(<span class="st">"bayesian"</span>) <span class="sc">/</span> <span class="fu">se_mgcv</span>(g_ri<span class="sc">$</span>Vp) <span class="sc">-</span> <span class="dv">1</span>)),</span>
<span id="cb10-9"><a href="#cb10-9" aria-hidden="true" tabindex="-1"></a>  <span class="at">frequentist =</span> <span class="fu">max</span>(<span class="fu">abs</span>(<span class="fu">se_sm</span>(<span class="st">"frequentist"</span>) <span class="sc">/</span> <span class="fu">se_mgcv</span>(g_ri<span class="sc">$</span>Ve) <span class="sc">-</span> <span class="dv">1</span>)))</span>
<span id="cb10-10"><a href="#cb10-10" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;     bayesian  frequentist </span></span>
<span id="cb10-11"><a href="#cb10-11" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 2.906475e-10 1.480441e-09</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</section>
</section>
<section id="sec-gamm-by" class="level2" data-number="9.2">
<h2 data-number="9.2" class="anchored" data-anchor-id="sec-gamm-by"><span class="header-section-number">9.2</span> A smooth for each group</h2>
<p>The chicks received four diets. As in <a href="06-gam.html#sec-gam-by" class="quarto-xref"><span>Section 6.4</span></a>, the argument <code>by = Diet</code> of <code>s()</code> builds one curve of time for each diet, and the main effect <code>Diet</code> carries the levels of the curves. We keep the random intercept and slope of each chick: <span class="math display">\[
\mu_{ij} = \beta_0 + \beta_{d(i)} + f_{d(i)}(t_{ij}) + b_{0i} + b_{1i} t_{ij},
\]</span> where <span class="math inline">\(d(i)\)</span> is the diet of chick <span class="math inline">\(i\)</span>. With <code>by_hyper = "shared"</code>, the default, the four curves have one smoothing parameter; with <code>by_hyper = "level"</code> each curve has its own.</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>fit_sh <span class="ot">&lt;-</span> <span class="fu">statmod</span>(weight <span class="sc">~</span> Diet <span class="sc">+</span> <span class="fu">s</span>(Time, <span class="fu">bspline_smooth</span>(<span class="at">k =</span> <span class="dv">8</span>), <span class="at">by =</span> Diet) <span class="sc">+</span></span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>                    <span class="fu">random</span>(<span class="sc">~</span> Time <span class="sc">|</span> Chick),</span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a>                  <span class="at">distrib =</span> <span class="fu">gaussian1_distrib</span>(), <span class="at">data =</span> ChickWeight)</span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a>fit_lv <span class="ot">&lt;-</span> <span class="fu">statmod</span>(weight <span class="sc">~</span> Diet <span class="sc">+</span> <span class="fu">s</span>(Time, <span class="fu">bspline_smooth</span>(<span class="at">k =</span> <span class="dv">8</span>), <span class="at">by =</span> Diet,</span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a>                                    <span class="at">by_hyper =</span> <span class="st">"level"</span>) <span class="sc">+</span></span>
<span id="cb11-6"><a href="#cb11-6" aria-hidden="true" tabindex="-1"></a>                    <span class="fu">random</span>(<span class="sc">~</span> Time <span class="sc">|</span> Chick),</span>
<span id="cb11-7"><a href="#cb11-7" aria-hidden="true" tabindex="-1"></a>                  <span class="at">distrib =</span> <span class="fu">gaussian1_distrib</span>(), <span class="at">data =</span> ChickWeight)</span>
<span id="cb11-8"><a href="#cb11-8" aria-hidden="true" tabindex="-1"></a><span class="fu">hyper</span>(fit_sh)[, <span class="fu">c</span>(<span class="st">"name"</span>, <span class="st">"estimate"</span>)]</span>
<span id="cb11-9"><a href="#cb11-9" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;           name    estimate</span></span>
<span id="cb11-10"><a href="#cb11-10" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 1       lambda  0.02854361</span></span>
<span id="cb11-11"><a href="#cb11-11" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 2 sigma_log_L1  2.43079371</span></span>
<span id="cb11-12"><a href="#cb11-12" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 3 sigma_log_L2  0.12644525</span></span>
<span id="cb11-13"><a href="#cb11-13" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 4   sigma_L2.1 -3.08219041</span></span>
<span id="cb11-14"><a href="#cb11-14" aria-hidden="true" tabindex="-1"></a><span class="fu">hyper</span>(fit_lv)[, <span class="fu">c</span>(<span class="st">"name"</span>, <span class="st">"estimate"</span>)]</span>
<span id="cb11-15"><a href="#cb11-15" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;           name    estimate</span></span>
<span id="cb11-16"><a href="#cb11-16" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 1       lambda  0.05962711</span></span>
<span id="cb11-17"><a href="#cb11-17" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 2       lambda  0.05213136</span></span>
<span id="cb11-18"><a href="#cb11-18" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 3       lambda  0.01395812</span></span>
<span id="cb11-19"><a href="#cb11-19" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 4       lambda  0.03295095</span></span>
<span id="cb11-20"><a href="#cb11-20" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 5 sigma_log_L1  2.43057188</span></span>
<span id="cb11-21"><a href="#cb11-21" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 6 sigma_log_L2  0.12632341</span></span>
<span id="cb11-22"><a href="#cb11-22" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 7   sigma_L2.1 -3.08280777</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>The smoothing parameter of diet 3 is about a quarter of those of diets 1 and 2, so its curve bends more, and that of diet 4 is in between. The model with one parameter is the model with four under three equality constraints, and the constrained values are inside the range of the parameters, so the likelihood ratio has three degrees of freedom:</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>l_sh <span class="ot">&lt;-</span> <span class="fu">as.numeric</span>(<span class="fu">logLik</span>(fit_sh, <span class="at">type =</span> <span class="st">"marginal"</span>))</span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>l_lv <span class="ot">&lt;-</span> <span class="fu">as.numeric</span>(<span class="fu">logLik</span>(fit_lv, <span class="at">type =</span> <span class="st">"marginal"</span>))</span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a>lr_by <span class="ot">&lt;-</span> <span class="dv">2</span> <span class="sc">*</span> (l_lv <span class="sc">-</span> l_sh)</span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a>lr_by</span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; [1] 1.725442</span></span>
<span id="cb12-6"><a href="#cb12-6" aria-hidden="true" tabindex="-1"></a><span class="fu">pchisq</span>(lr_by, <span class="at">df =</span> <span class="dv">3</span>, <span class="at">lower.tail =</span> <span class="cn">FALSE</span>)</span>
<span id="cb12-7"><a href="#cb12-7" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; [1] 0.6312924</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>The data do not need four smoothing parameters.</p>
<p>In <code>mgcv</code> a smooth with a factor <code>by</code> has one smoothing parameter for each level by default, and the argument <code>id</code> makes the levels share one. Its random effects are smooths with an identity penalty, so the intercept and the slope of a chick cannot be correlated there. With <code>correlated = FALSE</code> the two packages fit the same model:</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a>fit_shu <span class="ot">&lt;-</span> <span class="fu">statmod</span>(weight <span class="sc">~</span> Diet <span class="sc">+</span> <span class="fu">s</span>(Time, <span class="fu">bspline_smooth</span>(<span class="at">k =</span> <span class="dv">8</span>), <span class="at">by =</span> Diet) <span class="sc">+</span></span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>                     <span class="fu">random</span>(<span class="sc">~</span> Time <span class="sc">|</span> Chick, <span class="at">correlated =</span> <span class="cn">FALSE</span>),</span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a>                   <span class="at">distrib =</span> <span class="fu">gaussian1_distrib</span>(), <span class="at">data =</span> ChickWeight)</span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a>g_shu <span class="ot">&lt;-</span> mgcv<span class="sc">::</span><span class="fu">gam</span>(weight <span class="sc">~</span> Diet <span class="sc">+</span> <span class="fu">s</span>(Time, <span class="at">bs =</span> <span class="st">"bs"</span>, <span class="at">k =</span> <span class="dv">8</span>, <span class="at">by =</span> Diet, <span class="at">id =</span> <span class="dv">1</span>) <span class="sc">+</span></span>
<span id="cb13-5"><a href="#cb13-5" aria-hidden="true" tabindex="-1"></a>                     <span class="fu">s</span>(Chick, <span class="at">bs =</span> <span class="st">"re"</span>) <span class="sc">+</span> <span class="fu">s</span>(Chick, Time, <span class="at">bs =</span> <span class="st">"re"</span>),</span>
<span id="cb13-6"><a href="#cb13-6" aria-hidden="true" tabindex="-1"></a>                   <span class="at">data =</span> ChickWeight, <span class="at">method =</span> <span class="st">"REML"</span>)</span>
<span id="cb13-7"><a href="#cb13-7" aria-hidden="true" tabindex="-1"></a><span class="fu">max</span>(<span class="fu">abs</span>(<span class="fu">fitted</span>(fit_shu) <span class="sc">-</span> <span class="fu">fitted</span>(g_shu)))</span>
<span id="cb13-8"><a href="#cb13-8" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; [1] 9.545837e-07</span></span>
<span id="cb13-9"><a href="#cb13-9" aria-hidden="true" tabindex="-1"></a>edf_mu <span class="ot">&lt;-</span> <span class="cf">function</span>(fit) <span class="fu">sum</span>(fit<span class="sc">@</span>edf<span class="sc">$</span>edf[fit<span class="sc">@</span>edf<span class="sc">$</span>parameter <span class="sc">==</span> <span class="st">"mu"</span>])</span>
<span id="cb13-10"><a href="#cb13-10" aria-hidden="true" tabindex="-1"></a><span class="fu">c</span>(<span class="at">statmod =</span> <span class="fu">edf_mu</span>(fit_shu), <span class="at">mgcv =</span> <span class="fu">sum</span>(g_shu<span class="sc">$</span>edf))</span>
<span id="cb13-11"><a href="#cb13-11" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  statmod     mgcv </span></span>
<span id="cb13-12"><a href="#cb13-12" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 97.80878 97.80878</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p><a href="#fig-diets" class="quarto-xref">Figure&nbsp;<span>9.3</span></a> shows the curve of a typical chick of each diet with its 95% Bayesian band, and the curve of the model with one smoothing parameter for each diet. The two curves of a diet are close to each other and well inside the band. The bands of the four diets overlap during the first week, and the curves separate in the second and third weeks, when diet 3 gives the heaviest chicks and diet 1 the lightest.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-diets" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-diets-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="09-gamm_files/figure-html/fig-diets-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:100.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-diets-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;9.3: Weight against time for the chicks of each diet. The solid curve is a typical chick of the diet in the model with one smoothing parameter, with its 95% Bayesian band (shaded); the dashed curve is the model with one smoothing parameter for each diet.
</figcaption>
</figure>
</div>
</div>
</div>
<section id="sec-gamm-chick" class="level3">
<h3 class="anchored" data-anchor-id="sec-gamm-chick">A curve for each chick</h3>
<p>In the models so far a chick differs from the typical chick of its diet by a straight line, <span class="math inline">\(b_{0i} + b_{1i}t\)</span>. <a href="#fig-chicks" class="quarto-xref">Figure&nbsp;<span>9.1</span></a> shows that some chicks have curves of a different shape: some grow fast and then slow down, and others start slowly. A model with <code>s(Time, by = Chick)</code> alone gives each chick a smooth curve of its own. Each chick received one diet, so the curves of the chicks then contain the curves of the diets, and the model has nothing left to compare the diets. We keep the curves of the diets and add to each chick a smooth deviation from the curve of its diet: <span class="math display">\[
\mu_{ij} = \beta_0 + \beta_{d(i)} + f_{d(i)}(t_{ij}) + b_{0i} + b_{1i} t_{ij}
  + g_i(t_{ij}).
\]</span> The 50 deviations <span class="math inline">\(g_i\)</span> have one smoothing parameter, so the data of all the chicks determine how much a chick’s curve may bend. This is a hierarchical additive model in the sense of <span class="citation" data-cites="pedersen2019">Pedersen et al. (<a href="A2-references.html#ref-pedersen2019" role="doc-biblioref">2019</a>)</span>, with one curve for each diet in place of one curve for all the groups. The straight line of <span class="math inline">\(g_i\)</span> is already in the random intercept and slope, so we drop it with <code>null_space = "drop"</code>; then <span class="math inline">\(g_i\)</span> has no coefficient without a penalty. The deviations have 200 coefficients, most of them zero in each row of the design, and <code>sparse = TRUE</code> stores their block as a sparse matrix. The argument <code>label</code> gives the coefficients of the deviations the prefix <code>dev</code>, because the levels <code>1</code> to <code>4</code> of <code>Chick</code> would give them the same names as the curves of the four diets.</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>fit_gs <span class="ot">&lt;-</span> <span class="fu">statmod</span>(weight <span class="sc">~</span> Diet <span class="sc">+</span> <span class="fu">s</span>(Time, <span class="fu">bspline_smooth</span>(<span class="at">k =</span> <span class="dv">8</span>), <span class="at">by =</span> Diet) <span class="sc">+</span></span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>                    <span class="fu">random</span>(<span class="sc">~</span> Time <span class="sc">|</span> Chick) <span class="sc">+</span></span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a>                    <span class="fu">s</span>(Time, <span class="fu">bspline_smooth</span>(<span class="at">k =</span> <span class="dv">6</span>, <span class="at">null_space =</span> <span class="st">"drop"</span>), <span class="at">by =</span> Chick,</span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a>                      <span class="at">sparse =</span> <span class="cn">TRUE</span>, <span class="at">label =</span> <span class="st">"dev"</span>),</span>
<span id="cb14-5"><a href="#cb14-5" aria-hidden="true" tabindex="-1"></a>                  <span class="at">distrib =</span> <span class="fu">gaussian1_distrib</span>(), <span class="at">data =</span> ChickWeight)</span>
<span id="cb14-6"><a href="#cb14-6" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(fit_gs)</span>
<span id="cb14-7"><a href="#cb14-7" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; A statmod fit</span></span>
<span id="cb14-8"><a href="#cb14-8" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; </span></span>
<span id="cb14-9"><a href="#cb14-9" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; Call:  statmod(formula = weight ~ Diet + s(Time, bspline_smooth(k = 8), </span></span>
<span id="cb14-10"><a href="#cb14-10" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;             by = Diet) + random(~Time | Chick) + s(Time, bspline_smooth(k = 6, </span></span>
<span id="cb14-11"><a href="#cb14-11" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;             null_space = "drop"), by = Chick, sparse = TRUE, label = "dev"), </span></span>
<span id="cb14-12"><a href="#cb14-12" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;             distrib = gaussian1_distrib(), data = ChickWeight)</span></span>
<span id="cb14-13"><a href="#cb14-13" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; </span></span>
<span id="cb14-14"><a href="#cb14-14" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; Distribution: gaussian1     Observations: 578</span></span>
<span id="cb14-15"><a href="#cb14-15" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; </span></span>
<span id="cb14-16"><a href="#cb14-16" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; === mu   [identity link]</span></span>
<span id="cb14-17"><a href="#cb14-17" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; </span></span>
<span id="cb14-18"><a href="#cb14-18" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; Parametric terms</span></span>
<span id="cb14-19"><a href="#cb14-19" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;                estimate    se     z         p lower upper</span></span>
<span id="cb14-20"><a href="#cb14-20" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;   (Intercept)     99.96 5.881    17   &lt; 1e-16 88.43 111.5</span></span>
<span id="cb14-21"><a href="#cb14-21" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;   Diet2           20.92 10.03 2.085 0.0370755 1.254 40.58</span></span>
<span id="cb14-22"><a href="#cb14-22" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;   Diet3           40.63 10.03  4.05 5.119e-05 20.97  60.3</span></span>
<span id="cb14-23"><a href="#cb14-23" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;   Diet4           33.78 10.03 3.367 0.0007601 14.12 53.45</span></span>
<span id="cb14-24"><a href="#cb14-24" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; </span></span>
<span id="cb14-25"><a href="#cb14-25" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; s(Time, bspline_smooth(k = 8), by = Diet)   [28 coefficients, edf 22.97]</span></span>
<span id="cb14-26"><a href="#cb14-26" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;                  estimate       se     z         p    lower   upper</span></span>
<span id="cb14-27"><a href="#cb14-27" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;   lambda [reml]  0.009555 0.004297                 0.003958 0.02307</span></span>
<span id="cb14-28"><a href="#cb14-28" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;   1.lin             41.54    5.289 7.854 4.016e-15    31.17   51.91</span></span>
<span id="cb14-29"><a href="#cb14-29" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;   2.lin             58.05    7.289 7.964 1.670e-15    43.76   72.33</span></span>
<span id="cb14-30"><a href="#cb14-30" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;   3.lin             76.89    7.289 10.55   &lt; 1e-16     62.6   91.17</span></span>
<span id="cb14-31"><a href="#cb14-31" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;   4.lin             63.87    7.292 8.759   &lt; 1e-16    49.58   78.16</span></span>
<span id="cb14-32"><a href="#cb14-32" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; </span></span>
<span id="cb14-33"><a href="#cb14-33" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; random(~Time | Chick)   [100 coefficients, edf 87.35]</span></span>
<span id="cb14-34"><a href="#cb14-34" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;                                  estimate      se   lower   upper</span></span>
<span id="cb14-35"><a href="#cb14-35" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;   sd[(Intercept)] [reml]             12.9   1.402   10.43   15.96</span></span>
<span id="cb14-36"><a href="#cb14-36" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;   sd[Time] [reml]                   3.408  0.3638   2.764   4.201</span></span>
<span id="cb14-37"><a href="#cb14-37" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;   cor[(Intercept), Time] [reml]    -0.892 0.03227 -0.9404 -0.8083</span></span>
<span id="cb14-38"><a href="#cb14-38" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;   predicted effects (50 levels of Chick)</span></span>
<span id="cb14-39"><a href="#cb14-39" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;                    Min. 1st Qu.  Median Mean 3rd Qu.  Max.</span></span>
<span id="cb14-40"><a href="#cb14-40" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;     (Intercept)  -27.17  -8.921 -0.7386    0   9.497 26.13</span></span>
<span id="cb14-41"><a href="#cb14-41" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;     Time         -7.357  -1.856 -0.3333    0   2.176 6.956</span></span>
<span id="cb14-42"><a href="#cb14-42" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; </span></span>
<span id="cb14-43"><a href="#cb14-43" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; s(Time, bspline_smooth(k = 6, null_space = "drop"), by = Chick, sparse = TRUE, label = "dev")   [200 coefficients, edf 132.08]</span></span>
<span id="cb14-44"><a href="#cb14-44" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;                  estimate      se   lower   upper</span></span>
<span id="cb14-45"><a href="#cb14-45" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;   lambda [reml]  0.008031 0.00114 0.00608 0.01061</span></span>
<span id="cb14-46"><a href="#cb14-46" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; </span></span>
<span id="cb14-47"><a href="#cb14-47" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; === sigma   [log link]</span></span>
<span id="cb14-48"><a href="#cb14-48" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; </span></span>
<span id="cb14-49"><a href="#cb14-49" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; Parametric terms</span></span>
<span id="cb14-50"><a href="#cb14-50" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;                estimate      se     z       p lower upper</span></span>
<span id="cb14-51"><a href="#cb14-51" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;   (Intercept)     1.211 0.04141 29.25 &lt; 1e-16  1.13 1.293</span></span>
<span id="cb14-52"><a href="#cb14-52" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; </span></span>
<span id="cb14-53"><a href="#cb14-53" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 95% intervals, bayesian variance</span></span>
<span id="cb14-54"><a href="#cb14-54" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; conditional log-likelihood -1397.140330    effective df 247.40</span></span>
<span id="cb14-55"><a href="#cb14-55" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; cAIC 3289.083    cBIC 4367.647</span></span>
<span id="cb14-56"><a href="#cb14-56" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; fitted in 7.03 s</span></span>
<span id="cb14-57"><a href="#cb14-57" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; inner   max |grad|/se 6.1e-14   min eigen 0.00018</span></span>
<span id="cb14-58"><a href="#cb14-58" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; outer   max |grad|/se 2.4e-06   min eigen 0.2</span></span>
<span id="cb14-59"><a href="#cb14-59" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 1 note: print(summary(fit), notes = TRUE)</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>The summary has one block for each of the four terms of the mean. The parametric terms <code>Diet2</code>, <code>Diet3</code> and <code>Diet4</code> shift the curves of the diets up or down. Each curve of a diet also has a level of its own, set by the constraint that removes the constant from its basis, so these three coefficients are not the differences between the diets on a given day; those differences are read from the curves of <a href="#fig-diets" class="quarto-xref">Figure&nbsp;<span>9.3</span></a>. The block of the diet curves shows the one smoothing parameter of the four curves and the free straight line of each of them, <code>1.lin</code> to <code>4.lin</code>. As in <a href="01-model.html" class="quarto-xref"><span>Chapter 1</span></a>, each multiplies the time standardized to mean zero and standard deviation one over all the observations, so it is the slope of the linear part of the diet’s curve per standard deviation of time, 6.76 days. The slopes are largest for diet 3 and smallest for diet 1, as the curves of <a href="#fig-diets" class="quarto-xref">Figure&nbsp;<span>9.3</span></a> show. The block spends 23.0 effective degrees of freedom of its 28 coefficients. The block of the random intercept and slope reports the standard deviation of the chicks’ intercepts, 12.9 grams, and of their slopes, 3.41 grams a day, and their correlation, -0.89. The block <code>dev</code> has only one row: the smoothing parameter of the 50 deviations, with its standard error and interval. Its 200 coefficients are not printed, because each of them is the coordinate of one chick’s deviation in a basis and has no meaning of its own. The equation of <span class="math inline">\(\sigma\)</span> has only an intercept, on the log scale, so the residual standard deviation is <span class="math inline">\(\exp(1.211) = 3.36\)</span> grams. The last lines give the effective degrees of freedom of the whole model, 247.4 for 578 observations, and the conditional AIC.</p>
<p>With straight deviations the residual standard deviation was larger:</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="fu">c</span>(<span class="at">straight =</span> <span class="fu">exp</span>(<span class="fu">coef</span>(fit_sh)<span class="sc">$</span>sigma[[<span class="dv">1</span>]]), <span class="at">smooth =</span> <span class="fu">exp</span>(<span class="fu">coef</span>(fit_gs)<span class="sc">$</span>sigma[[<span class="dv">1</span>]]))</span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  straight    smooth </span></span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 10.727906  3.358214</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>The deviations spend 132.1 effective degrees of freedom of their 200 coefficients, about 2.6 for each chick. The residual standard deviation falls from 10.7 to 3.4 grams, so the residual variance falls by 90 per cent. Most of what the model with straight deviations left as noise is the shape of the chicks’ own curves. The two models have the same coefficients without a penalty, so their restricted log-likelihoods can be compared. Under the smaller model the variance <span class="math inline">\(1/\lambda\)</span> of the deviations is zero, on the boundary of its range, and the likelihood ratio has the distribution <span class="math inline">\(\tfrac12\chi^2_0 + \tfrac12\chi^2_1\)</span>:</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>l_gs <span class="ot">&lt;-</span> <span class="fu">as.numeric</span>(<span class="fu">logLik</span>(fit_gs, <span class="at">type =</span> <span class="st">"marginal"</span>))</span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>lr_gs <span class="ot">&lt;-</span> <span class="dv">2</span> <span class="sc">*</span> (l_gs <span class="sc">-</span> l_sh)</span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a>lr_gs</span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; [1] 664.3997</span></span>
<span id="cb16-5"><a href="#cb16-5" aria-hidden="true" tabindex="-1"></a><span class="fl">0.5</span> <span class="sc">*</span> <span class="fu">pchisq</span>(lr_gs, <span class="at">df =</span> <span class="dv">1</span>, <span class="at">lower.tail =</span> <span class="cn">FALSE</span>)</span>
<span id="cb16-6"><a href="#cb16-6" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; [1] 8.25039e-147</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>The curve of a typical chick of a diet is now <span class="math inline">\(\beta_0 + \beta_d + f_d(t)\)</span>, without <span class="math inline">\(b_{0i} + b_{1i}t\)</span> and without <span class="math inline">\(g_i\)</span>. <code>predict()</code> with <code>random = "zero"</code> sets the random intercept and slope to zero, but <span class="math inline">\(g_i\)</span> is a smooth and not a <code>random()</code> term, so <code>predict()</code> keeps it. We build the curve, and any other part of the predictor, from the columns of the design and from the same rows and columns of <code>vcov()</code>. The function <code>part_band()</code> takes the prefixes of the columns and the rows of the data where the part is wanted:</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a>part_band <span class="ot">&lt;-</span> <span class="cf">function</span>(fit, prefix, <span class="at">rows =</span> <span class="cn">NULL</span>, <span class="at">type =</span> <span class="st">"bayesian"</span>) {</span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>  X <span class="ot">&lt;-</span> <span class="fu">as.matrix</span>(<span class="fu">model.matrix</span>(fit))</span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a>  <span class="cf">if</span> (<span class="sc">!</span><span class="fu">is.null</span>(rows)) X <span class="ot">&lt;-</span> X[rows, , drop <span class="ot">=</span> <span class="cn">FALSE</span>]</span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a>  keep <span class="ot">&lt;-</span> <span class="fu">Reduce</span>(<span class="st">`</span><span class="at">|</span><span class="st">`</span>, <span class="fu">lapply</span>(prefix, <span class="cf">function</span>(p) <span class="fu">startsWith</span>(<span class="fu">colnames</span>(X), p)))</span>
<span id="cb17-5"><a href="#cb17-5" aria-hidden="true" tabindex="-1"></a>  nm <span class="ot">&lt;-</span> <span class="fu">colnames</span>(X)[keep]</span>
<span id="cb17-6"><a href="#cb17-6" aria-hidden="true" tabindex="-1"></a>  Xk <span class="ot">&lt;-</span> X[, nm, drop <span class="ot">=</span> <span class="cn">FALSE</span>]</span>
<span id="cb17-7"><a href="#cb17-7" aria-hidden="true" tabindex="-1"></a>  V <span class="ot">&lt;-</span> <span class="fu">as.matrix</span>(<span class="fu">vcov</span>(fit, <span class="at">type =</span> type)[<span class="fu">paste0</span>(<span class="st">"mu:"</span>, nm), <span class="fu">paste0</span>(<span class="st">"mu:"</span>, nm)])</span>
<span id="cb17-8"><a href="#cb17-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">data.frame</span>(<span class="at">fit =</span> <span class="fu">drop</span>(Xk <span class="sc">%*%</span> <span class="fu">coef</span>(fit)<span class="sc">$</span>mu[nm]),</span>
<span id="cb17-9"><a href="#cb17-9" aria-hidden="true" tabindex="-1"></a>             <span class="at">se =</span> <span class="fu">sqrt</span>(<span class="fu">rowSums</span>((Xk <span class="sc">%*%</span> V) <span class="sc">*</span> Xk)))</span>
<span id="cb17-10"><a href="#cb17-10" aria-hidden="true" tabindex="-1"></a>}</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>On the model of <a href="#sec-gamm-intercept" class="quarto-xref"><span>Section 9.1</span></a> the part <code>s(Time)</code> is the contribution of the smooth, which sums to zero over the data, and it has the value and the standard error that <code>mgcv</code> reports with <code>type = "terms"</code>:</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a>p_ri <span class="ot">&lt;-</span> <span class="fu">part_band</span>(fit_ri, <span class="at">prefix =</span> <span class="st">"s(Time)."</span>)</span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a>t_ri <span class="ot">&lt;-</span> <span class="fu">predict</span>(g_ri, <span class="at">type =</span> <span class="st">"terms"</span>, <span class="at">se.fit =</span> <span class="cn">TRUE</span>)</span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a><span class="fu">c</span>(<span class="at">fit =</span> <span class="fu">max</span>(<span class="fu">abs</span>(p_ri<span class="sc">$</span>fit <span class="sc">-</span> t_ri<span class="sc">$</span>fit[, <span class="st">"s(Time)"</span>])),</span>
<span id="cb18-4"><a href="#cb18-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">se =</span> <span class="fu">max</span>(<span class="fu">abs</span>(p_ri<span class="sc">$</span>se <span class="sc">-</span> t_ri<span class="sc">$</span>se.fit[, <span class="st">"s(Time)"</span>])))</span>
<span id="cb18-5"><a href="#cb18-5" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;          fit           se </span></span>
<span id="cb18-6"><a href="#cb18-6" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 1.386113e-08 3.270786e-09</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>The curve of diet 3 is the part with the prefixes <code>(Intercept)</code>, <code>Diet3</code> and <code>s(Time).3.</code>. We read it at the twelve days of chick 33, which received diet 3 and was weighed on every day:</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a>r33 <span class="ot">&lt;-</span> <span class="fu">which</span>(ChickWeight<span class="sc">$</span>Chick <span class="sc">==</span> <span class="st">"33"</span>)</span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a>d3 <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"(Intercept)"</span>, <span class="st">"Diet3"</span>, <span class="st">"s(Time).3."</span>)</span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a><span class="fu">rbind</span>(<span class="at">day =</span> ChickWeight<span class="sc">$</span>Time[r33],</span>
<span id="cb19-4"><a href="#cb19-4" aria-hidden="true" tabindex="-1"></a>      <span class="at">straight =</span> <span class="fu">part_band</span>(fit_sh, <span class="at">prefix =</span> d3, <span class="at">rows =</span> r33)<span class="sc">$</span>fit,</span>
<span id="cb19-5"><a href="#cb19-5" aria-hidden="true" tabindex="-1"></a>      <span class="at">smooth =</span> <span class="fu">part_band</span>(fit_gs, <span class="at">prefix =</span> d3, <span class="at">rows =</span> r33)<span class="sc">$</span>fit)</span>
<span id="cb19-6"><a href="#cb19-6" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;              [,1]     [,2]    [,3]     [,4]     [,5]     [,6]     [,7]     [,8]</span></span>
<span id="cb19-7"><a href="#cb19-7" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; day       0.00000  2.00000  4.0000  6.00000  8.00000  10.0000  12.0000  14.0000</span></span>
<span id="cb19-8"><a href="#cb19-8" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; straight 39.10764 50.52973 63.3930 78.94921 97.30058 118.2342 142.0118 168.9874</span></span>
<span id="cb19-9"><a href="#cb19-9" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; smooth   38.28104 49.13831 61.8323 79.02119 99.35408 120.5549 143.2788 169.3063</span></span>
<span id="cb19-10"><a href="#cb19-10" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;              [,9]    [,10]    [,11]    [,12]</span></span>
<span id="cb19-11"><a href="#cb19-11" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; day       16.0000  18.0000  20.0000  21.0000</span></span>
<span id="cb19-12"><a href="#cb19-12" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; straight 198.2746 228.2838 257.9285 272.3994</span></span>
<span id="cb19-13"><a href="#cb19-13" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; smooth   198.5429 229.5702 257.7618 268.5719</span></span>
<span id="cb19-14"><a href="#cb19-14" aria-hidden="true" tabindex="-1"></a><span class="fu">rbind</span>(<span class="at">straight =</span> <span class="fu">part_band</span>(fit_sh, <span class="at">prefix =</span> d3, <span class="at">rows =</span> r33)<span class="sc">$</span>se,</span>
<span id="cb19-15"><a href="#cb19-15" aria-hidden="true" tabindex="-1"></a>      <span class="at">smooth =</span> <span class="fu">part_band</span>(fit_gs, <span class="at">prefix =</span> d3, <span class="at">rows =</span> r33)<span class="sc">$</span>se)</span>
<span id="cb19-16"><a href="#cb19-16" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;              [,1]     [,2]     [,3]     [,4]     [,5]     [,6]      [,7]     [,8]</span></span>
<span id="cb19-17"><a href="#cb19-17" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; straight 4.625733 2.671585 2.477158 3.637492 5.450499 7.356266  9.375528 11.39236</span></span>
<span id="cb19-18"><a href="#cb19-18" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; smooth   6.795533 3.616914 2.408936 4.160293 6.357020 8.339237 10.229640 12.02935</span></span>
<span id="cb19-19"><a href="#cb19-19" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;              [,9]    [,10]    [,11]    [,12]</span></span>
<span id="cb19-20"><a href="#cb19-20" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; straight 13.44755 15.48707 17.55939 18.66281</span></span>
<span id="cb19-21"><a href="#cb19-21" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; smooth   13.87412 15.93268 18.34610 19.70093</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>The curve of diet 3 is the same in the two models to within 4 grams. Its band is a little wider when the deviations are smooth, although the residual standard deviation is three times smaller. As in <a href="#sec-gamm-band" class="quarto-xref"><span>Section 9.1.2</span></a>, most of the standard error of a typical curve is the variation among chicks, and with smooth deviations the chicks vary in the shape of their curves as well as in their intercept and slope.</p>
<p><a href="#fig-gs" class="quarto-xref">Figure&nbsp;<span>9.4</span></a> shows the six chicks whose curves change most between the two models. With a straight deviation the curve of a chick has the shape of the curve of its diet. With a smooth deviation it follows the chick’s own weights: chicks 33 and 11 stop growing in the last week, and chicks 29 and 7 grow faster than the curve of their diet in the third week. The straight deviation cannot describe these shapes, and to come close to the late weights of chick 33 it puts the weight at birth about 20 grams too high.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-gs" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-gs-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="09-gamm_files/figure-html/fig-gs-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:100.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-gs-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;9.4: Six chicks: their weights, the fitted curve with a smooth deviation from the diet’s curve (solid) and with a straight deviation (dashed), and the curve of a typical chick of the diet (dotted).
</figcaption>
</figure>
</div>
</div>
</div>
</section>
</section>
<section id="sec-gamm-sigma" class="level2" data-number="9.3">
<h2 data-number="9.3" class="anchored" data-anchor-id="sec-gamm-sigma"><span class="header-section-number">9.3</span> Smooths and random effects in sigma</h2>
<p>The spread of the weights around a chick’s curve also grows with age, and some chicks are more variable than others. We give the equation of <span class="math inline">\(\sigma\)</span> a smooth of time and a random intercept of its own: <span class="math display">\[
\log\sigma_{ij} = \gamma_0 + g(t_{ij}) + c_i, \qquad
c_i \sim \mathrm{N}(0, \kappa),
\]</span> independent of the random intercept <span class="math inline">\(b_i\)</span> of the mean.</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a>fit_sg0 <span class="ot">&lt;-</span> <span class="fu">statmod</span>(weight <span class="sc">~</span> Diet <span class="sc">+</span> <span class="fu">s</span>(Time, <span class="fu">bspline_smooth</span>(<span class="at">k =</span> <span class="dv">8</span>)) <span class="sc">+</span></span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a>                     <span class="fu">random</span>(<span class="sc">~</span> <span class="dv">1</span> <span class="sc">|</span> Chick) <span class="sc">|</span></span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a>                     sigma <span class="sc">~</span> <span class="fu">s</span>(Time, <span class="fu">bspline_smooth</span>(<span class="at">k =</span> <span class="dv">8</span>)),</span>
<span id="cb20-4"><a href="#cb20-4" aria-hidden="true" tabindex="-1"></a>                   <span class="at">distrib =</span> <span class="fu">gaussian1_distrib</span>(), <span class="at">data =</span> ChickWeight)</span>
<span id="cb20-5"><a href="#cb20-5" aria-hidden="true" tabindex="-1"></a>fit_sg <span class="ot">&lt;-</span> <span class="fu">statmod</span>(weight <span class="sc">~</span> Diet <span class="sc">+</span> <span class="fu">s</span>(Time, <span class="fu">bspline_smooth</span>(<span class="at">k =</span> <span class="dv">8</span>)) <span class="sc">+</span></span>
<span id="cb20-6"><a href="#cb20-6" aria-hidden="true" tabindex="-1"></a>                    <span class="fu">random</span>(<span class="sc">~</span> <span class="dv">1</span> <span class="sc">|</span> Chick) <span class="sc">|</span></span>
<span id="cb20-7"><a href="#cb20-7" aria-hidden="true" tabindex="-1"></a>                    sigma <span class="sc">~</span> <span class="fu">s</span>(Time, <span class="fu">bspline_smooth</span>(<span class="at">k =</span> <span class="dv">8</span>)) <span class="sc">+</span> <span class="fu">random</span>(<span class="sc">~</span> <span class="dv">1</span> <span class="sc">|</span> Chick),</span>
<span id="cb20-8"><a href="#cb20-8" aria-hidden="true" tabindex="-1"></a>                  <span class="at">distrib =</span> <span class="fu">gaussian1_distrib</span>(), <span class="at">data =</span> ChickWeight)</span>
<span id="cb20-9"><a href="#cb20-9" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(fit_sg)</span>
<span id="cb20-10"><a href="#cb20-10" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; A statmod fit</span></span>
<span id="cb20-11"><a href="#cb20-11" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; </span></span>
<span id="cb20-12"><a href="#cb20-12" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; Call:  statmod(formula = weight ~ Diet + s(Time, bspline_smooth(k = 8)) + </span></span>
<span id="cb20-13"><a href="#cb20-13" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;             random(~1 | Chick) | sigma ~ s(Time, bspline_smooth(k = 8)) + </span></span>
<span id="cb20-14"><a href="#cb20-14" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;             random(~1 | Chick), distrib = gaussian1_distrib(), data = ChickWeight)</span></span>
<span id="cb20-15"><a href="#cb20-15" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; </span></span>
<span id="cb20-16"><a href="#cb20-16" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; Distribution: gaussian1     Observations: 578</span></span>
<span id="cb20-17"><a href="#cb20-17" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; </span></span>
<span id="cb20-18"><a href="#cb20-18" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; === mu   [identity link]</span></span>
<span id="cb20-19"><a href="#cb20-19" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; </span></span>
<span id="cb20-20"><a href="#cb20-20" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; Parametric terms</span></span>
<span id="cb20-21"><a href="#cb20-21" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;                estimate     se        z         p     lower  upper</span></span>
<span id="cb20-22"><a href="#cb20-22" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;   (Intercept)     123.9  1.036    119.6   &lt; 1e-16     121.9  125.9</span></span>
<span id="cb20-23"><a href="#cb20-23" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;   Diet2        -0.02104 0.4825 -0.04361 0.9652160   -0.9666 0.9246</span></span>
<span id="cb20-24"><a href="#cb20-24" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;   Diet3          0.9599 0.4912    1.954 0.0507071 -0.002954  1.923</span></span>
<span id="cb20-25"><a href="#cb20-25" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;   Diet4           1.863 0.4828    3.859 0.0001137     0.917  2.809</span></span>
<span id="cb20-26"><a href="#cb20-26" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; </span></span>
<span id="cb20-27"><a href="#cb20-27" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; s(Time, bspline_smooth(k = 8))   [7 coefficients, edf 4.76]</span></span>
<span id="cb20-28"><a href="#cb20-28" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;                  estimate      se     z       p    lower  upper</span></span>
<span id="cb20-29"><a href="#cb20-29" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;   lambda [reml]   0.03009 0.02136               0.007487 0.1209</span></span>
<span id="cb20-30"><a href="#cb20-30" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;   lin               61.53   1.173 52.45 &lt; 1e-16    59.23  63.83</span></span>
<span id="cb20-31"><a href="#cb20-31" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; </span></span>
<span id="cb20-32"><a href="#cb20-32" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; random(~1 | Chick)   [50 coefficients, edf 13.48]</span></span>
<span id="cb20-33"><a href="#cb20-33" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;                 estimate     se  lower upper</span></span>
<span id="cb20-34"><a href="#cb20-34" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;   sigma [reml]    0.6798 0.1842 0.3997 1.156</span></span>
<span id="cb20-35"><a href="#cb20-35" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;   predicted effects (50 levels of Chick)</span></span>
<span id="cb20-36"><a href="#cb20-36" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;                    Min. 1st Qu.  Median Mean 3rd Qu.   Max.</span></span>
<span id="cb20-37"><a href="#cb20-37" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;     (Intercept)  -1.016 -0.2156 0.08392    0  0.2394 0.9473</span></span>
<span id="cb20-38"><a href="#cb20-38" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; </span></span>
<span id="cb20-39"><a href="#cb20-39" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; === sigma   [log link]</span></span>
<span id="cb20-40"><a href="#cb20-40" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; </span></span>
<span id="cb20-41"><a href="#cb20-41" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; Parametric terms</span></span>
<span id="cb20-42"><a href="#cb20-42" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;                estimate      se     z       p lower upper</span></span>
<span id="cb20-43"><a href="#cb20-43" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;   (Intercept)     2.656 0.07815 33.98 &lt; 1e-16 2.502 2.809</span></span>
<span id="cb20-44"><a href="#cb20-44" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; </span></span>
<span id="cb20-45"><a href="#cb20-45" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; s(Time, bspline_smooth(k = 8))   [7 coefficients, edf 3.87]</span></span>
<span id="cb20-46"><a href="#cb20-46" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;                  estimate      se     z       p lower upper</span></span>
<span id="cb20-47"><a href="#cb20-47" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;   lambda [reml]      20.8   28.89               1.366 316.6</span></span>
<span id="cb20-48"><a href="#cb20-48" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;   lin               1.189 0.03887 30.59 &lt; 1e-16 1.113 1.265</span></span>
<span id="cb20-49"><a href="#cb20-49" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; </span></span>
<span id="cb20-50"><a href="#cb20-50" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; random(~1 | Chick)   [50 coefficients, edf 41.59]</span></span>
<span id="cb20-51"><a href="#cb20-51" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;                 estimate      se  lower  upper</span></span>
<span id="cb20-52"><a href="#cb20-52" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;   sigma [reml]    0.5046 0.06222 0.3963 0.6426</span></span>
<span id="cb20-53"><a href="#cb20-53" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;   predicted effects (50 levels of Chick)</span></span>
<span id="cb20-54"><a href="#cb20-54" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;                     Min. 1st Qu.   Median     Mean 3rd Qu.   Max.</span></span>
<span id="cb20-55"><a href="#cb20-55" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;     (Intercept)  -0.9517 -0.4257 -0.06862 -0.05339  0.2886 0.8737</span></span>
<span id="cb20-56"><a href="#cb20-56" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; </span></span>
<span id="cb20-57"><a href="#cb20-57" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 95% intervals, bayesian variance</span></span>
<span id="cb20-58"><a href="#cb20-58" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; conditional log-likelihood -2303.691359    effective df 68.69</span></span>
<span id="cb20-59"><a href="#cb20-59" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; cAIC 4744.767    cBIC 5044.234</span></span>
<span id="cb20-60"><a href="#cb20-60" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; fitted in 6.22 s</span></span>
<span id="cb20-61"><a href="#cb20-61" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; inner   max |grad|/se 7.6e-14   min eigen 0.0013</span></span>
<span id="cb20-62"><a href="#cb20-62" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; outer   max |grad|/se 3.8e-06   min eigen 0.7</span></span>
<span id="cb20-63"><a href="#cb20-63" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 1 note: print(summary(fit), notes = TRUE)</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>The random intercepts of <span class="math inline">\(\log\sigma\)</span> have a standard deviation of <span class="math inline">\(\hat\kappa = 0.50\)</span>: the residual standard deviation of one chick can be <span class="math inline">\(\exp(1.96\,\hat\kappa) = 2.7\)</span> times larger or smaller than that of a typical chick. The two models have the same fixed effects in the mean, and under the smaller one <span class="math inline">\(\kappa^2\)</span> is zero, on the boundary of its range, so the likelihood ratio has the distribution <span class="math inline">\(\tfrac12\chi^2_0 + \tfrac12\chi^2_1\)</span> <span class="citation" data-cites="self1987">(<a href="A2-references.html#ref-self1987" role="doc-biblioref">Self and Liang 1987</a>)</span>:</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a>lr_sg <span class="ot">&lt;-</span> <span class="dv">2</span> <span class="sc">*</span> (<span class="fu">as.numeric</span>(<span class="fu">logLik</span>(fit_sg, <span class="at">type =</span> <span class="st">"marginal"</span>)) <span class="sc">-</span></span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a>                <span class="fu">as.numeric</span>(<span class="fu">logLik</span>(fit_sg0, <span class="at">type =</span> <span class="st">"marginal"</span>)))</span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a>lr_sg</span>
<span id="cb21-4"><a href="#cb21-4" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; [1] 143.6151</span></span>
<span id="cb21-5"><a href="#cb21-5" aria-hidden="true" tabindex="-1"></a><span class="fl">0.5</span> <span class="sc">*</span> <span class="fu">pchisq</span>(lr_sg, <span class="at">df =</span> <span class="dv">1</span>, <span class="at">lower.tail =</span> <span class="cn">FALSE</span>)</span>
<span id="cb21-6"><a href="#cb21-6" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; [1] 2.156321e-33</span></span>
<span id="cb21-7"><a href="#cb21-7" aria-hidden="true" tabindex="-1"></a><span class="fu">c</span>(<span class="at">without =</span> <span class="fu">hyper</span>(fit_sg0)<span class="sc">$</span>estimate[<span class="dv">2</span>], <span class="at">with =</span> <span class="fu">hyper</span>(fit_sg)<span class="sc">$</span>estimate[<span class="dv">2</span>])</span>
<span id="cb21-8"><a href="#cb21-8" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;   without      with </span></span>
<span id="cb21-9"><a href="#cb21-9" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 0.5350684 0.6798146</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>The last line gives the standard deviation of the chicks’ intercepts in the mean, without and with the random effects in <span class="math inline">\(\sigma\)</span>: 0.54 and 0.68 grams. In the model of <a href="#sec-gamm-intercept" class="quarto-xref"><span>Section 9.1</span></a>, with a constant <span class="math inline">\(\sigma\)</span>, it was 26.8 grams. A chick that grows faster than the others has its weights close to the typical curve at the start and far from it at the end. With a constant <span class="math inline">\(\sigma\)</span> the model describes this with a large random intercept, which shifts the whole curve of the chick. With a <span class="math inline">\(\sigma\)</span> that grows with time it describes it with a residual spread that grows, and the random intercept is left with the small differences at birth.</p>
<p>In <code>glmmTMB()</code> the equation of <span class="math inline">\(\sigma\)</span> is the argument <code>dispformula</code>, which accepts a smooth and a random effect:</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a>tmb_sg <span class="ot">&lt;-</span> glmmTMB<span class="sc">::</span><span class="fu">glmmTMB</span>(weight <span class="sc">~</span> Diet <span class="sc">+</span> <span class="fu">s</span>(Time, <span class="at">bs =</span> <span class="st">"bs"</span>, <span class="at">k =</span> <span class="dv">8</span>) <span class="sc">+</span> (<span class="dv">1</span> <span class="sc">|</span> Chick),</span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a>                           <span class="at">dispformula =</span> <span class="sc">~</span> <span class="fu">s</span>(Time, <span class="at">bs =</span> <span class="st">"bs"</span>, <span class="at">k =</span> <span class="dv">8</span>) <span class="sc">+</span> (<span class="dv">1</span> <span class="sc">|</span> Chick),</span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a>                           <span class="at">data =</span> ChickWeight, <span class="at">REML =</span> <span class="cn">TRUE</span>)</span>
<span id="cb22-4"><a href="#cb22-4" aria-hidden="true" tabindex="-1"></a>glmmTMB<span class="sc">::</span><span class="fu">VarCorr</span>(tmb_sg)</span>
<span id="cb22-5"><a href="#cb22-5" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; </span></span>
<span id="cb22-6"><a href="#cb22-6" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; Conditional model:</span></span>
<span id="cb22-7"><a href="#cb22-7" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  Groups   Name        Std.Dev.</span></span>
<span id="cb22-8"><a href="#cb22-8" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  dummy    dummy1      3.79944 </span></span>
<span id="cb22-9"><a href="#cb22-9" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  Chick    (Intercept) 0.66523 </span></span>
<span id="cb22-10"><a href="#cb22-10" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  Residual                  NA </span></span>
<span id="cb22-11"><a href="#cb22-11" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; </span></span>
<span id="cb22-12"><a href="#cb22-12" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; Dispersion model:</span></span>
<span id="cb22-13"><a href="#cb22-13" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  Groups   Name        Std.Dev.</span></span>
<span id="cb22-14"><a href="#cb22-14" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  dummy    dummy1      0.10669 </span></span>
<span id="cb22-15"><a href="#cb22-15" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  Chick    (Intercept) 0.50383 </span></span>
<span id="cb22-16"><a href="#cb22-16" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  Residual                  NA</span></span>
<span id="cb22-17"><a href="#cb22-17" aria-hidden="true" tabindex="-1"></a><span class="fu">max</span>(<span class="fu">abs</span>(<span class="fu">fitted</span>(fit_sg) <span class="sc">-</span> <span class="fu">fitted</span>(tmb_sg)))</span>
<span id="cb22-18"><a href="#cb22-18" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; [1] 0.5519508</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>The standard deviations differ by less than 3 per cent, and the fitted means differ by up to 0.55 grams. The difference comes from the smooth of <span class="math inline">\(\sigma\)</span>. A smooth with a penalty on the second derivative splits into a straight line, which the penalty leaves free, and a wiggly part, which the penalty shrinks. The split is not unique, because a straight line can be added to the wiggly part, and <code>statmodels7</code> and <code>mgcv</code> (whose smooths <code>glmmTMB</code> uses) make different choices. REML integrates the straight line of the mean, and then the choice changes the criterion only by the constant of <a href="#sec-gamm-intercept" class="quarto-xref"><span>Section 9.1</span></a>. The straight line of <span class="math inline">\(\sigma\)</span> is not integrated but estimated (<a href="02-beyond.html#sec-beyond-outer" class="quarto-xref"><span>Section 2.8</span></a>), and then the prior of the wiggly part, and so the estimates, depend on the choice. The same happens to the smooth of the mean under maximum likelihood, which estimates its straight line:</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a>fit_ml <span class="ot">&lt;-</span> <span class="fu">statmod</span>(weight <span class="sc">~</span> <span class="fu">s</span>(Time, <span class="fu">bspline_smooth</span>(<span class="at">k =</span> <span class="dv">8</span>)),</span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a>                  <span class="at">distrib =</span> <span class="fu">gaussian1_distrib</span>(), <span class="at">data =</span> ChickWeight,</span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a>                  <span class="at">outer_criterion =</span> <span class="fu">ml</span>(<span class="at">marginal =</span> <span class="st">"all"</span>))</span>
<span id="cb23-4"><a href="#cb23-4" aria-hidden="true" tabindex="-1"></a>g_ml <span class="ot">&lt;-</span> mgcv<span class="sc">::</span><span class="fu">gam</span>(weight <span class="sc">~</span> <span class="fu">s</span>(Time, <span class="at">bs =</span> <span class="st">"bs"</span>, <span class="at">k =</span> <span class="dv">8</span>), <span class="at">data =</span> ChickWeight,</span>
<span id="cb23-5"><a href="#cb23-5" aria-hidden="true" tabindex="-1"></a>                  <span class="at">method =</span> <span class="st">"ML"</span>)</span>
<span id="cb23-6"><a href="#cb23-6" aria-hidden="true" tabindex="-1"></a><span class="fu">c</span>(<span class="at">statmod =</span> <span class="fu">exp</span>(<span class="fu">coef</span>(fit_ml)<span class="sc">$</span>sigma[[<span class="dv">1</span>]]), <span class="at">mgcv =</span> <span class="fu">sqrt</span>(g_ml<span class="sc">$</span>sig2))</span>
<span id="cb23-7"><a href="#cb23-7" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  statmod     mgcv </span></span>
<span id="cb23-8"><a href="#cb23-8" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 38.39060 38.45863</span></span>
<span id="cb23-9"><a href="#cb23-9" aria-hidden="true" tabindex="-1"></a><span class="fu">c</span>(<span class="at">statmod =</span> <span class="fu">as.numeric</span>(<span class="fu">logLik</span>(fit_ml, <span class="at">type =</span> <span class="st">"marginal"</span>)), <span class="at">mgcv =</span> <span class="sc">-</span>g_ml<span class="sc">$</span>gcv.ubre)</span>
<span id="cb23-10"><a href="#cb23-10" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;   statmod   mgcv.ML </span></span>
<span id="cb23-11"><a href="#cb23-11" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; -2930.227 -2930.709</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>The two maxima differ: they are maxima of two slightly different models.</p>
<p><a href="#fig-sigma" class="quarto-xref">Figure&nbsp;<span>9.5</span></a> shows the residual standard deviation of a typical chick against time, with the interval that holds the standard deviation of 95% of the chicks (<code>interval = "group"</code>, <a href="08-glmm.html#sec-glmm-predict" class="quarto-xref"><span>Section 8.5</span></a>).</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-sigma" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-sigma-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="09-gamm_files/figure-html/fig-sigma-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:100.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-sigma-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;9.5: Residual standard deviation of the weight against time: a typical chick (solid) and the interval that holds 95% of the chicks (dashed).
</figcaption>
</figure>
</div>
</div>
</div>
</section>
<section id="sec-gamm-counts" class="level2" data-number="9.4">
<h2 data-number="9.4" class="anchored" data-anchor-id="sec-gamm-counts"><span class="header-section-number">9.4</span> A model for counts</h2>
<p>We return to the barn owls of <a href="08-glmm.html#sec-glmm-negbin" class="quarto-xref"><span>Section 8.3</span></a>: the number of calls of the nestlings in 27 nests before a parent arrived <span class="citation" data-cites="roulin2007">(<a href="A2-references.html#ref-roulin2007" role="doc-biblioref">Roulin and Bersier 2007</a>)</span>. The parents arrived between about 21:40 and 5:15, and <span class="citation" data-cites="zuur2009">Zuur et al. (<a href="A2-references.html#ref-zuur2009" role="doc-biblioref">2009</a>)</span> found that the number of calls changes with the time of arrival. We add a smooth of the arrival time to the negative binomial model of <a href="08-glmm.html#sec-glmm-negbin" class="quarto-xref"><span>Section 8.3</span></a>: <span class="math display">\[
\log\mu_{ij} = \log n_{ij} + x_{ij}^\top\beta + f(t_{ij}) + b_i, \qquad
b_i \sim \mathrm{N}(0, \tau),
\]</span> where <span class="math inline">\(n_{ij}\)</span> is the number of nestlings and <span class="math inline">\(t_{ij}\)</span> the arrival time, in hours after midnight of the previous day (25 is 1:00 in the morning).</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(Owls, <span class="at">package =</span> <span class="st">"glmmTMB"</span>)</span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a>fit_ow <span class="ot">&lt;-</span> <span class="fu">statmod</span>(SiblingNegotiation <span class="sc">~</span> FoodTreatment <span class="sc">*</span> SexParent <span class="sc">+</span></span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a>                    <span class="fu">offset</span>(logBroodSize) <span class="sc">+</span> <span class="fu">s</span>(ArrivalTime, <span class="fu">bspline_smooth</span>(<span class="at">k =</span> <span class="dv">10</span>)) <span class="sc">+</span></span>
<span id="cb24-4"><a href="#cb24-4" aria-hidden="true" tabindex="-1"></a>                    <span class="fu">random</span>(<span class="sc">~</span> <span class="dv">1</span> <span class="sc">|</span> Nest),</span>
<span id="cb24-5"><a href="#cb24-5" aria-hidden="true" tabindex="-1"></a>                  <span class="at">distrib =</span> <span class="fu">negbin2_distrib</span>(), <span class="at">data =</span> Owls)</span>
<span id="cb24-6"><a href="#cb24-6" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(fit_ow)</span>
<span id="cb24-7"><a href="#cb24-7" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; A statmod fit</span></span>
<span id="cb24-8"><a href="#cb24-8" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; </span></span>
<span id="cb24-9"><a href="#cb24-9" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; Call:  statmod(formula = SiblingNegotiation ~ FoodTreatment * SexParent + </span></span>
<span id="cb24-10"><a href="#cb24-10" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;             offset(logBroodSize) + s(ArrivalTime, bspline_smooth(k = 10)) + </span></span>
<span id="cb24-11"><a href="#cb24-11" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;             random(~1 | Nest), distrib = negbin2_distrib(), data = Owls)</span></span>
<span id="cb24-12"><a href="#cb24-12" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; </span></span>
<span id="cb24-13"><a href="#cb24-13" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; Distribution: negbin2     Observations: 599</span></span>
<span id="cb24-14"><a href="#cb24-14" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; </span></span>
<span id="cb24-15"><a href="#cb24-15" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; === mu   [log link]</span></span>
<span id="cb24-16"><a href="#cb24-16" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; </span></span>
<span id="cb24-17"><a href="#cb24-17" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; Parametric terms</span></span>
<span id="cb24-18"><a href="#cb24-18" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;                                        estimate     se       z         p   lower   upper</span></span>
<span id="cb24-19"><a href="#cb24-19" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;   (Intercept)                            0.6468  0.129   5.015 5.315e-07   0.394  0.8996</span></span>
<span id="cb24-20"><a href="#cb24-20" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;   FoodTreatmentSatiated                 -0.8172 0.1501  -5.446 5.153e-08  -1.111 -0.5231</span></span>
<span id="cb24-21"><a href="#cb24-21" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;   SexParentMale                        -0.02552 0.1355 -0.1884    0.8506 -0.2911  0.2401</span></span>
<span id="cb24-22"><a href="#cb24-22" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;   FoodTreatmentSatiated:SexParentMale    0.1856 0.1922  0.9656    0.3343 -0.1912  0.5624</span></span>
<span id="cb24-23"><a href="#cb24-23" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; </span></span>
<span id="cb24-24"><a href="#cb24-24" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; s(ArrivalTime, bspline_smooth(k = 10))   [9 coefficients, edf 6.31]</span></span>
<span id="cb24-25"><a href="#cb24-25" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;                  estimate      se      z       p   lower   upper</span></span>
<span id="cb24-26"><a href="#cb24-26" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;   lambda [reml]    0.8544  0.6569                 0.1893   3.856</span></span>
<span id="cb24-27"><a href="#cb24-27" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;   lin             -0.2161 0.04706 -4.592 4.4e-06 -0.3083 -0.1238</span></span>
<span id="cb24-28"><a href="#cb24-28" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; </span></span>
<span id="cb24-29"><a href="#cb24-29" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; random(~1 | Nest)   [27 coefficients, edf 17.12]</span></span>
<span id="cb24-30"><a href="#cb24-30" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;                 estimate      se  lower  upper</span></span>
<span id="cb24-31"><a href="#cb24-31" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;   sigma [reml]    0.3728 0.08799 0.2347 0.5921</span></span>
<span id="cb24-32"><a href="#cb24-32" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;   predicted effects (27 levels of Nest)</span></span>
<span id="cb24-33"><a href="#cb24-33" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;                    Min. 1st Qu.  Median Mean 3rd Qu.   Max.</span></span>
<span id="cb24-34"><a href="#cb24-34" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;     (Intercept)  -0.662 -0.1647 0.01044    0  0.1882 0.5705</span></span>
<span id="cb24-35"><a href="#cb24-35" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; </span></span>
<span id="cb24-36"><a href="#cb24-36" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; === theta   [log link]</span></span>
<span id="cb24-37"><a href="#cb24-37" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; </span></span>
<span id="cb24-38"><a href="#cb24-38" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; Parametric terms</span></span>
<span id="cb24-39"><a href="#cb24-39" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;                estimate      se      z     p   lower  upper</span></span>
<span id="cb24-40"><a href="#cb24-40" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;   (Intercept)  -0.04156 0.08263 -0.503 0.615 -0.2035 0.1204</span></span>
<span id="cb24-41"><a href="#cb24-41" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; </span></span>
<span id="cb24-42"><a href="#cb24-42" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 95% intervals, bayesian variance</span></span>
<span id="cb24-43"><a href="#cb24-43" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; conditional log-likelihood -1687.874445    effective df 28.43</span></span>
<span id="cb24-44"><a href="#cb24-44" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; cAIC 3432.611    cBIC 3557.571</span></span>
<span id="cb24-45"><a href="#cb24-45" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; fitted in 520 ms</span></span>
<span id="cb24-46"><a href="#cb24-46" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; inner   max |grad|/se 1.4e-15   min eigen 0.058</span></span>
<span id="cb24-47"><a href="#cb24-47" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; outer   max |grad|/se 3.2e-08   min eigen 0.88</span></span>
<span id="cb24-48"><a href="#cb24-48" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 1 note: print(summary(fit), notes = TRUE)</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>The family <code>nb()</code> of <code>mgcv</code> estimates <span class="math inline">\(\theta\)</span> together with the smoothing parameters, and <code>glmmTMB()</code> accepts the smooth with the family <code>nbinom2</code>:</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a>g_ow <span class="ot">&lt;-</span> mgcv<span class="sc">::</span><span class="fu">gam</span>(SiblingNegotiation <span class="sc">~</span> FoodTreatment <span class="sc">*</span> SexParent <span class="sc">+</span></span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a>                    <span class="fu">offset</span>(logBroodSize) <span class="sc">+</span> <span class="fu">s</span>(ArrivalTime, <span class="at">bs =</span> <span class="st">"bs"</span>, <span class="at">k =</span> <span class="dv">10</span>) <span class="sc">+</span></span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a>                    <span class="fu">s</span>(Nest, <span class="at">bs =</span> <span class="st">"re"</span>),</span>
<span id="cb25-4"><a href="#cb25-4" aria-hidden="true" tabindex="-1"></a>                  <span class="at">family =</span> mgcv<span class="sc">::</span><span class="fu">nb</span>(), <span class="at">data =</span> Owls, <span class="at">method =</span> <span class="st">"REML"</span>)</span>
<span id="cb25-5"><a href="#cb25-5" aria-hidden="true" tabindex="-1"></a>tmb_ow <span class="ot">&lt;-</span> glmmTMB<span class="sc">::</span><span class="fu">glmmTMB</span>(SiblingNegotiation <span class="sc">~</span> FoodTreatment <span class="sc">*</span> SexParent <span class="sc">+</span></span>
<span id="cb25-6"><a href="#cb25-6" aria-hidden="true" tabindex="-1"></a>                             <span class="fu">offset</span>(logBroodSize) <span class="sc">+</span></span>
<span id="cb25-7"><a href="#cb25-7" aria-hidden="true" tabindex="-1"></a>                             <span class="fu">s</span>(ArrivalTime, <span class="at">bs =</span> <span class="st">"bs"</span>, <span class="at">k =</span> <span class="dv">10</span>) <span class="sc">+</span> (<span class="dv">1</span> <span class="sc">|</span> Nest),</span>
<span id="cb25-8"><a href="#cb25-8" aria-hidden="true" tabindex="-1"></a>                           <span class="at">family =</span> glmmTMB<span class="sc">::</span>nbinom2, <span class="at">data =</span> Owls, <span class="at">REML =</span> <span class="cn">TRUE</span>)</span>
<span id="cb25-9"><a href="#cb25-9" aria-hidden="true" tabindex="-1"></a><span class="fu">c</span>(<span class="at">statmod =</span> <span class="fu">exp</span>(<span class="fu">coef</span>(fit_ow)<span class="sc">$</span>theta[[<span class="dv">1</span>]]),</span>
<span id="cb25-10"><a href="#cb25-10" aria-hidden="true" tabindex="-1"></a>  <span class="at">mgcv =</span> g_ow<span class="sc">$</span>family<span class="sc">$</span><span class="fu">getTheta</span>(<span class="cn">TRUE</span>), <span class="at">glmmTMB =</span> glmmTMB<span class="sc">::</span><span class="fu">sigma</span>(tmb_ow))</span>
<span id="cb25-11"><a href="#cb25-11" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;   statmod      mgcv   glmmTMB </span></span>
<span id="cb25-12"><a href="#cb25-12" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 0.9592876 0.9592876 0.9592854</span></span>
<span id="cb25-13"><a href="#cb25-13" aria-hidden="true" tabindex="-1"></a><span class="fu">max</span>(<span class="fu">abs</span>(<span class="fu">predict</span>(fit_ow, <span class="at">what =</span> <span class="st">"link:mu"</span>) <span class="sc">-</span> <span class="fu">predict</span>(g_ow, <span class="at">type =</span> <span class="st">"link"</span>)))</span>
<span id="cb25-14"><a href="#cb25-14" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; [1] 6.078251e-09</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p><a href="#fig-owls" class="quarto-xref">Figure&nbsp;<span>9.6</span></a> shows the calls per nestling of a typical nest against the arrival time. The nestlings call most when a parent arrives at about 22:40, and least when it arrives near midnight and near 3:00. The model has no interaction between the food treatment and the time, so on the log scale the two curves differ by a constant, and the food-deprived nestlings call more at every hour. The bands are widest at the two ends of the night, where few parents arrived.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-owls" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-owls-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="09-gamm_files/figure-html/fig-owls-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:100.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-owls-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;9.6: Calls per nestling against the arrival time of the parent, for a typical nest with a male parent: food-deprived (solid) and satiated (dashed) nestlings, with 95% Bayesian bands (shaded). The points are the observed calls per nestling.
</figcaption>
</figure>
</div>
</div>
</div>
<section id="random-effects-on-the-dispersion" class="level3">
<h3 class="anchored" data-anchor-id="random-effects-on-the-dispersion">Random effects on the dispersion</h3>
<p>As in <a href="08-glmm.html#sec-glmm-negbin" class="quarto-xref"><span>Section 8.3</span></a> we let <span class="math inline">\(\theta\)</span> depend on the food treatment and on the nest:</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a>fit_ow2 <span class="ot">&lt;-</span> <span class="fu">statmod</span>(SiblingNegotiation <span class="sc">~</span> FoodTreatment <span class="sc">*</span> SexParent <span class="sc">+</span></span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a>                     <span class="fu">offset</span>(logBroodSize) <span class="sc">+</span> <span class="fu">s</span>(ArrivalTime, <span class="fu">bspline_smooth</span>(<span class="at">k =</span> <span class="dv">10</span>)) <span class="sc">+</span></span>
<span id="cb26-3"><a href="#cb26-3" aria-hidden="true" tabindex="-1"></a>                     <span class="fu">random</span>(<span class="sc">~</span> <span class="dv">1</span> <span class="sc">|</span> Nest) <span class="sc">|</span></span>
<span id="cb26-4"><a href="#cb26-4" aria-hidden="true" tabindex="-1"></a>                     theta <span class="sc">~</span> FoodTreatment <span class="sc">+</span> <span class="fu">random</span>(<span class="sc">~</span> <span class="dv">1</span> <span class="sc">|</span> Nest),</span>
<span id="cb26-5"><a href="#cb26-5" aria-hidden="true" tabindex="-1"></a>                   <span class="at">distrib =</span> <span class="fu">negbin2_distrib</span>(), <span class="at">data =</span> Owls)</span>
<span id="cb26-6"><a href="#cb26-6" aria-hidden="true" tabindex="-1"></a><span class="fu">hyper</span>(fit_ow2)[, <span class="fu">c</span>(<span class="st">"parameter"</span>, <span class="st">"name"</span>, <span class="st">"estimate"</span>)]</span>
<span id="cb26-7"><a href="#cb26-7" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;   parameter   name estimate</span></span>
<span id="cb26-8"><a href="#cb26-8" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 1        mu lambda 1.808185</span></span>
<span id="cb26-9"><a href="#cb26-9" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 2        mu  sigma 0.204138</span></span>
<span id="cb26-10"><a href="#cb26-10" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 3     theta  sigma 0.861120</span></span>
<span id="cb26-11"><a href="#cb26-11" aria-hidden="true" tabindex="-1"></a>tmb_ow2 <span class="ot">&lt;-</span> glmmTMB<span class="sc">::</span><span class="fu">glmmTMB</span>(SiblingNegotiation <span class="sc">~</span> FoodTreatment <span class="sc">*</span> SexParent <span class="sc">+</span></span>
<span id="cb26-12"><a href="#cb26-12" aria-hidden="true" tabindex="-1"></a>                              <span class="fu">offset</span>(logBroodSize) <span class="sc">+</span></span>
<span id="cb26-13"><a href="#cb26-13" aria-hidden="true" tabindex="-1"></a>                              <span class="fu">s</span>(ArrivalTime, <span class="at">bs =</span> <span class="st">"bs"</span>, <span class="at">k =</span> <span class="dv">10</span>) <span class="sc">+</span> (<span class="dv">1</span> <span class="sc">|</span> Nest),</span>
<span id="cb26-14"><a href="#cb26-14" aria-hidden="true" tabindex="-1"></a>                            <span class="at">dispformula =</span> <span class="sc">~</span> FoodTreatment <span class="sc">+</span> (<span class="dv">1</span> <span class="sc">|</span> Nest),</span>
<span id="cb26-15"><a href="#cb26-15" aria-hidden="true" tabindex="-1"></a>                            <span class="at">family =</span> glmmTMB<span class="sc">::</span>nbinom2, <span class="at">data =</span> Owls, <span class="at">REML =</span> <span class="cn">TRUE</span>)</span>
<span id="cb26-16"><a href="#cb26-16" aria-hidden="true" tabindex="-1"></a>glmmTMB<span class="sc">::</span><span class="fu">VarCorr</span>(tmb_ow2)</span>
<span id="cb26-17"><a href="#cb26-17" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; </span></span>
<span id="cb26-18"><a href="#cb26-18" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; Conditional model:</span></span>
<span id="cb26-19"><a href="#cb26-19" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  Groups Name        Std.Dev.</span></span>
<span id="cb26-20"><a href="#cb26-20" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  dummy  dummy1      0.39502 </span></span>
<span id="cb26-21"><a href="#cb26-21" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  Nest   (Intercept) 0.20414 </span></span>
<span id="cb26-22"><a href="#cb26-22" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; </span></span>
<span id="cb26-23"><a href="#cb26-23" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; Dispersion model:</span></span>
<span id="cb26-24"><a href="#cb26-24" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  Groups Name        Std.Dev.</span></span>
<span id="cb26-25"><a href="#cb26-25" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  Nest   (Intercept) 0.86112</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>The two models have the same fixed effects in the mean and the same smooth, so the constant of <a href="#sec-gamm-intercept" class="quarto-xref"><span>Section 9.1</span></a> cancels in the difference of their restricted log-likelihoods, and the two packages give the same likelihood ratio:</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a>lr_ow <span class="ot">&lt;-</span> <span class="dv">2</span> <span class="sc">*</span> (<span class="fu">as.numeric</span>(<span class="fu">logLik</span>(fit_ow2, <span class="at">type =</span> <span class="st">"marginal"</span>)) <span class="sc">-</span></span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a>                <span class="fu">as.numeric</span>(<span class="fu">logLik</span>(fit_ow, <span class="at">type =</span> <span class="st">"marginal"</span>)))</span>
<span id="cb27-3"><a href="#cb27-3" aria-hidden="true" tabindex="-1"></a>lr_ow_tmb <span class="ot">&lt;-</span> <span class="dv">2</span> <span class="sc">*</span> (<span class="fu">as.numeric</span>(<span class="fu">logLik</span>(tmb_ow2)) <span class="sc">-</span> <span class="fu">as.numeric</span>(<span class="fu">logLik</span>(tmb_ow)))</span>
<span id="cb27-4"><a href="#cb27-4" aria-hidden="true" tabindex="-1"></a><span class="fu">c</span>(<span class="at">statmod =</span> lr_ow, <span class="at">glmmTMB =</span> lr_ow_tmb)</span>
<span id="cb27-5"><a href="#cb27-5" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  statmod  glmmTMB </span></span>
<span id="cb27-6"><a href="#cb27-6" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 113.9219 113.9219</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</section>
</section>
<section id="sec-gamm-id" class="level2" data-number="9.5">
<h2 data-number="9.5" class="anchored" data-anchor-id="sec-gamm-id"><span class="header-section-number">9.5</span> Shared smoothing parameters</h2>
<p>The argument <code>by_hyper</code> decides whether the curves of one factor share a smoothing parameter. The argument <code>id</code> of <code>s()</code>, <code>te()</code>, <code>random()</code> and the penalized terms is more general: the hyperparameters of all the terms with the same <code>id</code> are estimated at one value, wherever the terms are in the formula.</p>
<section id="lagged-covariates" class="level3">
<h3 class="anchored" data-anchor-id="lagged-covariates">Lagged covariates</h3>
<p>A typical use is a covariate that enters the model at several lags. In the Chicago data of <a href="06-gam.html#sec-gam-counts" class="quarto-xref"><span>Section 6.7</span></a> the deaths of a day may depend on the temperature of that day and of the two days before. The three curves describe the same kind of effect, and it is natural to smooth them by the same amount: <span class="math display">\[
\log\mu_t = x_t^\top\beta + h(t) + f_0(T_t) + f_1(T_{t-1}) + f_2(T_{t-2}),
\]</span> where <span class="math inline">\(h\)</span> is a smooth of the date, <span class="math inline">\(x_t\)</span> is the day of the week and <span class="math inline">\(T_t\)</span> the mean temperature of day <span class="math inline">\(t\)</span>.</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(chicagoNMMAPS, <span class="at">package =</span> <span class="st">"dlnm"</span>)</span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a>chicagoNMMAPS <span class="ot">&lt;-</span> chicagoNMMAPS[chicagoNMMAPS<span class="sc">$</span>year <span class="sc">&gt;=</span> <span class="dv">1995</span> <span class="sc">&amp;</span></span>
<span id="cb28-3"><a href="#cb28-3" aria-hidden="true" tabindex="-1"></a>                                 chicagoNMMAPS<span class="sc">$</span>year <span class="sc">&lt;=</span> <span class="dv">2000</span>, ]</span>
<span id="cb28-4"><a href="#cb28-4" aria-hidden="true" tabindex="-1"></a>chicagoNMMAPS<span class="sc">$</span>temp1 <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="cn">NA</span>, <span class="fu">head</span>(chicagoNMMAPS<span class="sc">$</span>temp, <span class="sc">-</span><span class="dv">1</span>))</span>
<span id="cb28-5"><a href="#cb28-5" aria-hidden="true" tabindex="-1"></a>chicagoNMMAPS<span class="sc">$</span>temp2 <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="cn">NA</span>, <span class="cn">NA</span>, <span class="fu">head</span>(chicagoNMMAPS<span class="sc">$</span>temp, <span class="sc">-</span><span class="dv">2</span>))</span>
<span id="cb28-6"><a href="#cb28-6" aria-hidden="true" tabindex="-1"></a>chicagoNMMAPS <span class="ot">&lt;-</span> chicagoNMMAPS[<span class="sc">-</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">2</span>), ]</span>
<span id="cb28-7"><a href="#cb28-7" aria-hidden="true" tabindex="-1"></a>fit_id <span class="ot">&lt;-</span> <span class="fu">statmod</span>(death <span class="sc">~</span> dow <span class="sc">+</span> <span class="fu">s</span>(time, <span class="fu">bspline_smooth</span>(<span class="at">k =</span> <span class="dv">24</span>)) <span class="sc">+</span></span>
<span id="cb28-8"><a href="#cb28-8" aria-hidden="true" tabindex="-1"></a>                    <span class="fu">s</span>(temp, <span class="fu">bspline_smooth</span>(<span class="at">k =</span> <span class="dv">8</span>), <span class="at">id =</span> <span class="st">"T"</span>) <span class="sc">+</span></span>
<span id="cb28-9"><a href="#cb28-9" aria-hidden="true" tabindex="-1"></a>                    <span class="fu">s</span>(temp1, <span class="fu">bspline_smooth</span>(<span class="at">k =</span> <span class="dv">8</span>), <span class="at">id =</span> <span class="st">"T"</span>) <span class="sc">+</span></span>
<span id="cb28-10"><a href="#cb28-10" aria-hidden="true" tabindex="-1"></a>                    <span class="fu">s</span>(temp2, <span class="fu">bspline_smooth</span>(<span class="at">k =</span> <span class="dv">8</span>), <span class="at">id =</span> <span class="st">"T"</span>),</span>
<span id="cb28-11"><a href="#cb28-11" aria-hidden="true" tabindex="-1"></a>                  <span class="at">distrib =</span> <span class="fu">poisson_distrib</span>(), <span class="at">data =</span> chicagoNMMAPS)</span>
<span id="cb28-12"><a href="#cb28-12" aria-hidden="true" tabindex="-1"></a>fit_free <span class="ot">&lt;-</span> <span class="fu">statmod</span>(death <span class="sc">~</span> dow <span class="sc">+</span> <span class="fu">s</span>(time, <span class="fu">bspline_smooth</span>(<span class="at">k =</span> <span class="dv">24</span>)) <span class="sc">+</span></span>
<span id="cb28-13"><a href="#cb28-13" aria-hidden="true" tabindex="-1"></a>                      <span class="fu">s</span>(temp, <span class="fu">bspline_smooth</span>(<span class="at">k =</span> <span class="dv">8</span>)) <span class="sc">+</span></span>
<span id="cb28-14"><a href="#cb28-14" aria-hidden="true" tabindex="-1"></a>                      <span class="fu">s</span>(temp1, <span class="fu">bspline_smooth</span>(<span class="at">k =</span> <span class="dv">8</span>)) <span class="sc">+</span></span>
<span id="cb28-15"><a href="#cb28-15" aria-hidden="true" tabindex="-1"></a>                      <span class="fu">s</span>(temp2, <span class="fu">bspline_smooth</span>(<span class="at">k =</span> <span class="dv">8</span>)),</span>
<span id="cb28-16"><a href="#cb28-16" aria-hidden="true" tabindex="-1"></a>                    <span class="at">distrib =</span> <span class="fu">poisson_distrib</span>(), <span class="at">data =</span> chicagoNMMAPS)</span>
<span id="cb28-17"><a href="#cb28-17" aria-hidden="true" tabindex="-1"></a><span class="fu">hyper</span>(fit_id)[, <span class="fu">c</span>(<span class="st">"term"</span>, <span class="st">"estimate"</span>)]</span>
<span id="cb28-18"><a href="#cb28-18" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;                                        term  estimate</span></span>
<span id="cb28-19"><a href="#cb28-19" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 1           s(time, bspline_smooth(k = 24))  1.103748</span></span>
<span id="cb28-20"><a href="#cb28-20" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 2  s(temp, bspline_smooth(k = 8), id = "T") 12.202182</span></span>
<span id="cb28-21"><a href="#cb28-21" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 3 s(temp1, bspline_smooth(k = 8), id = "T") 12.202182</span></span>
<span id="cb28-22"><a href="#cb28-22" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 4 s(temp2, bspline_smooth(k = 8), id = "T") 12.202182</span></span>
<span id="cb28-23"><a href="#cb28-23" aria-hidden="true" tabindex="-1"></a><span class="fu">hyper</span>(fit_free)[, <span class="fu">c</span>(<span class="st">"term"</span>, <span class="st">"estimate"</span>)]</span>
<span id="cb28-24"><a href="#cb28-24" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;                              term    estimate</span></span>
<span id="cb28-25"><a href="#cb28-25" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 1 s(time, bspline_smooth(k = 24))    1.104042</span></span>
<span id="cb28-26"><a href="#cb28-26" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 2  s(temp, bspline_smooth(k = 8)) 1777.561112</span></span>
<span id="cb28-27"><a href="#cb28-27" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 3 s(temp1, bspline_smooth(k = 8))   16.539335</span></span>
<span id="cb28-28"><a href="#cb28-28" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 4 s(temp2, bspline_smooth(k = 8))    5.254421</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>The <code>id</code> of <code>mgcv</code> does the same:</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a>g_id <span class="ot">&lt;-</span> mgcv<span class="sc">::</span><span class="fu">gam</span>(death <span class="sc">~</span> dow <span class="sc">+</span> <span class="fu">s</span>(time, <span class="at">bs =</span> <span class="st">"bs"</span>, <span class="at">k =</span> <span class="dv">24</span>) <span class="sc">+</span></span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a>                    <span class="fu">s</span>(temp, <span class="at">bs =</span> <span class="st">"bs"</span>, <span class="at">k =</span> <span class="dv">8</span>, <span class="at">id =</span> <span class="dv">1</span>) <span class="sc">+</span></span>
<span id="cb29-3"><a href="#cb29-3" aria-hidden="true" tabindex="-1"></a>                    <span class="fu">s</span>(temp1, <span class="at">bs =</span> <span class="st">"bs"</span>, <span class="at">k =</span> <span class="dv">8</span>, <span class="at">id =</span> <span class="dv">1</span>) <span class="sc">+</span></span>
<span id="cb29-4"><a href="#cb29-4" aria-hidden="true" tabindex="-1"></a>                    <span class="fu">s</span>(temp2, <span class="at">bs =</span> <span class="st">"bs"</span>, <span class="at">k =</span> <span class="dv">8</span>, <span class="at">id =</span> <span class="dv">1</span>),</span>
<span id="cb29-5"><a href="#cb29-5" aria-hidden="true" tabindex="-1"></a>                  <span class="at">family =</span> poisson, <span class="at">data =</span> chicagoNMMAPS, <span class="at">method =</span> <span class="st">"REML"</span>)</span>
<span id="cb29-6"><a href="#cb29-6" aria-hidden="true" tabindex="-1"></a><span class="fu">max</span>(<span class="fu">abs</span>(<span class="fu">predict</span>(fit_id, <span class="at">what =</span> <span class="st">"link:mu"</span>) <span class="sc">-</span> <span class="fu">predict</span>(g_id, <span class="at">type =</span> <span class="st">"link"</span>)))</span>
<span id="cb29-7"><a href="#cb29-7" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; [1] 6.677595e-06</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>The shared parameter is a constraint on the free ones, inside their range, so we compare the two models with a likelihood ratio on two degrees of freedom:</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a>lr_id <span class="ot">&lt;-</span> <span class="dv">2</span> <span class="sc">*</span> (<span class="fu">as.numeric</span>(<span class="fu">logLik</span>(fit_free, <span class="at">type =</span> <span class="st">"marginal"</span>)) <span class="sc">-</span></span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a>                <span class="fu">as.numeric</span>(<span class="fu">logLik</span>(fit_id, <span class="at">type =</span> <span class="st">"marginal"</span>)))</span>
<span id="cb30-3"><a href="#cb30-3" aria-hidden="true" tabindex="-1"></a>lr_id</span>
<span id="cb30-4"><a href="#cb30-4" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; [1] 20.34617</span></span>
<span id="cb30-5"><a href="#cb30-5" aria-hidden="true" tabindex="-1"></a><span class="fu">pchisq</span>(lr_id, <span class="at">df =</span> <span class="dv">2</span>, <span class="at">lower.tail =</span> <span class="cn">FALSE</span>)</span>
<span id="cb30-6"><a href="#cb30-6" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; [1] 3.818444e-05</span></span>
<span id="cb30-7"><a href="#cb30-7" aria-hidden="true" tabindex="-1"></a>fit_free<span class="sc">@</span>edf[<span class="dv">3</span><span class="sc">:</span><span class="dv">5</span>, <span class="fu">c</span>(<span class="st">"term"</span>, <span class="st">"edf"</span>)]</span>
<span id="cb30-8"><a href="#cb30-8" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;                              term      edf</span></span>
<span id="cb30-9"><a href="#cb30-9" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 3  s(temp, bspline_smooth(k = 8)) 4.187574</span></span>
<span id="cb30-10"><a href="#cb30-10" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 4 s(temp1, bspline_smooth(k = 8)) 6.653427</span></span>
<span id="cb30-11"><a href="#cb30-11" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 5 s(temp2, bspline_smooth(k = 8)) 6.881659</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Here the data reject the shared parameter. With three free parameters the curve of the same day’s temperature is smoothed much more than the other two: it spends 4.2 effective degrees of freedom of its 7 coefficients, against 6.7 and 6.9 for the two previous days.</p>
<p>The function <code>part_band()</code> of <a href="#sec-gamm-chick" class="quarto-xref"><span>Section 9.2.1</span></a> gives the contribution <span class="math inline">\(f_k(T)\)</span> of each curve with its band. The contribution sums to zero over the data, and its band leaves out the uncertainty of the intercept. <a href="#fig-lags" class="quarto-xref">Figure&nbsp;<span>9.7</span></a> shows the three curves of the two models as ratios of the death rate, <span class="math inline">\(\exp\{f_k(T)\}\)</span>, with their 95% bands.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-lags" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-lags-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="09-gamm_files/figure-html/fig-lags-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:100.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-lags-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;9.7: Ratio of the daily death rate to the rate at the average of the smooth, against the temperature of the same day (lag 0) and of the two days before (lags 1 and 2), with one shared smoothing parameter (solid, band shaded) and one for each lag (dashed, band dashed).
</figcaption>
</figure>
</div>
</div>
</div>
<p>The three temperatures are strongly correlated, so each curve is the effect of the temperature of one day with the temperatures of the other two days held fixed. On 98 days of 100 the two models give curves that differ by less than half a per cent in the rate. The shared parameter changes the curves at their ends, where the data are few, and most of all the curve of the same day: with its own parameter this curve is smoother, flatter on the coldest days and less steep on the hottest. This is the difference that the likelihood ratio detects. It does not change what the curves say about the effect of temperature on mortality. Heat acts within two days. The highest mean temperature in the data, 33.3 degrees, was reached on 13 July 1995, during the Chicago heat wave of July 1995. At this temperature the rate ratio is 1.49 when it is the temperature of the day before and 1.91 when it is the temperature of two days before. Cold acts later: at lag 2 a temperature of <span class="math inline">\(-15\)</span> degrees multiplies the rate by 1.10, while on the same day the cold lowers it a little.</p>
</section>
<section id="levels-that-share-a-parameter" class="level3">
<h3 class="anchored" data-anchor-id="levels-that-share-a-parameter">Levels that share a parameter</h3>
<p><code>id</code> also groups some levels of a factor <code>by</code>. Under <code>by_hyper = "level"</code> the hyperparameters of the levels are named <code>lambda.1</code>, <code>lambda.2</code> and so on, and <code>id</code> takes one label for each of them. In <a href="#sec-gamm-by" class="quarto-xref"><span>Section 9.2</span></a> the smoothing parameter of diet 3 was the smallest, so we let diets 1, 2 and 4 share one parameter and give diet 3 its own:</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a>fit_lid <span class="ot">&lt;-</span> <span class="fu">statmod</span>(weight <span class="sc">~</span> Diet <span class="sc">+</span></span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a>                     <span class="fu">s</span>(Time, <span class="fu">bspline_smooth</span>(<span class="at">k =</span> <span class="dv">8</span>), <span class="at">by =</span> Diet, <span class="at">by_hyper =</span> <span class="st">"level"</span>,</span>
<span id="cb31-3"><a href="#cb31-3" aria-hidden="true" tabindex="-1"></a>                       <span class="at">id =</span> <span class="fu">c</span>(<span class="at">lambda.1 =</span> <span class="st">"A"</span>, <span class="at">lambda.2 =</span> <span class="st">"A"</span>, <span class="at">lambda.3 =</span> <span class="st">"B"</span>,</span>
<span id="cb31-4"><a href="#cb31-4" aria-hidden="true" tabindex="-1"></a>                              <span class="at">lambda.4 =</span> <span class="st">"A"</span>)) <span class="sc">+</span></span>
<span id="cb31-5"><a href="#cb31-5" aria-hidden="true" tabindex="-1"></a>                     <span class="fu">random</span>(<span class="sc">~</span> Time <span class="sc">|</span> Chick),</span>
<span id="cb31-6"><a href="#cb31-6" aria-hidden="true" tabindex="-1"></a>                   <span class="at">distrib =</span> <span class="fu">gaussian1_distrib</span>(), <span class="at">data =</span> ChickWeight)</span>
<span id="cb31-7"><a href="#cb31-7" aria-hidden="true" tabindex="-1"></a><span class="fu">hyper</span>(fit_lid)[, <span class="fu">c</span>(<span class="st">"name"</span>, <span class="st">"estimate"</span>)]</span>
<span id="cb31-8"><a href="#cb31-8" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;           name    estimate</span></span>
<span id="cb31-9"><a href="#cb31-9" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 1       lambda  0.05144394</span></span>
<span id="cb31-10"><a href="#cb31-10" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 2       lambda  0.05144394</span></span>
<span id="cb31-11"><a href="#cb31-11" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 3       lambda  0.01396034</span></span>
<span id="cb31-12"><a href="#cb31-12" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 4       lambda  0.05144394</span></span>
<span id="cb31-13"><a href="#cb31-13" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 5 sigma_log_L1  2.43049831</span></span>
<span id="cb31-14"><a href="#cb31-14" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 6 sigma_log_L2  0.12545011</span></span>
<span id="cb31-15"><a href="#cb31-15" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 7   sigma_L2.1 -3.08312911</span></span>
<span id="cb31-16"><a href="#cb31-16" aria-hidden="true" tabindex="-1"></a>l_lid <span class="ot">&lt;-</span> <span class="fu">as.numeric</span>(<span class="fu">logLik</span>(fit_lid, <span class="at">type =</span> <span class="st">"marginal"</span>))</span>
<span id="cb31-17"><a href="#cb31-17" aria-hidden="true" tabindex="-1"></a>lr_lid <span class="ot">&lt;-</span> <span class="dv">2</span> <span class="sc">*</span> (l_lv <span class="sc">-</span> l_lid)</span>
<span id="cb31-18"><a href="#cb31-18" aria-hidden="true" tabindex="-1"></a>lr_lid</span>
<span id="cb31-19"><a href="#cb31-19" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; [1] 0.09938119</span></span>
<span id="cb31-20"><a href="#cb31-20" aria-hidden="true" tabindex="-1"></a><span class="fu">pchisq</span>(lr_lid, <span class="at">df =</span> <span class="dv">2</span>, <span class="at">lower.tail =</span> <span class="cn">FALSE</span>)</span>
<span id="cb31-21"><a href="#cb31-21" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; [1] 0.9515238</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>The model with two smoothing parameters is the model with four under two equality constraints, and the likelihood ratio does not reject them: diets 1, 2 and 4 can share one smoothing parameter, and diet 3 keeps its own.</p>


<div id="refs" class="references csl-bib-body hanging-indent" data-entry-spacing="0" role="list" style="display: none">
<div id="ref-brooks2017" class="csl-entry" role="listitem">
Brooks, Mollie E., Kasper Kristensen, Koen J. van Benthem, Arni Magnusson, Casper W. Berg, Anders Nielsen, Hans J. Skaug, Martin Mächler, and Benjamin M. Bolker. 2017. <span>“<span class="nocase">glmmTMB</span> Balances Speed and Flexibility Among Packages for Zero-Inflated Generalized Linear Mixed Modeling.”</span> <em>The R Journal</em> 9 (2): 378–400.
</div>
<div id="ref-crowder1990" class="csl-entry" role="listitem">
Crowder, Martin J., and David J. Hand. 1990. <em>Analysis of Repeated Measures</em>. London: Chapman; Hall.
</div>
<div id="ref-lin1999" class="csl-entry" role="listitem">
Lin, Xihong, and Daowen Zhang. 1999. <span>“Inference in Generalized Additive Mixed Models by Using Smoothing Splines.”</span> <em>Journal of the Royal Statistical Society: Series B</em> 61 (2): 381–400.
</div>
<div id="ref-pedersen2019" class="csl-entry" role="listitem">
Pedersen, Eric J., David L. Miller, Gavin L. Simpson, and Noam Ross. 2019. <span>“Hierarchical Generalized Additive Models in Ecology: An Introduction with Mgcv.”</span> <em>PeerJ</em> 7: e6876.
</div>
<div id="ref-roulin2007" class="csl-entry" role="listitem">
Roulin, A., and L.-F. Bersier. 2007. <span>“Nestling Barn Owls Beg More Intensely in the Presence of Their Mother Than in the Presence of Their Father.”</span> <em>Animal Behaviour</em> 74: 1099–1106.
</div>
<div id="ref-ruppert2003" class="csl-entry" role="listitem">
Ruppert, David, M. P. Wand, and R. J. Carroll. 2003. <em>Semiparametric Regression</em>. Cambridge: Cambridge University Press.
</div>
<div id="ref-self1987" class="csl-entry" role="listitem">
Self, Steven G., and Kung-Yee Liang. 1987. <span>“Asymptotic Properties of Maximum Likelihood Estimators and Likelihood Ratio Tests Under Nonstandard Conditions.”</span> <em>Journal of the American Statistical Association</em> 82 (398): 605–10.
</div>
<div id="ref-wood2017" class="csl-entry" role="listitem">
Wood, Simon N. 2017. <em>Generalized Additive Models: An Introduction with r</em>. 2nd ed. Boca Raton: Chapman; Hall/CRC.
</div>
<div id="ref-zuur2009" class="csl-entry" role="listitem">
Zuur, A. F., E. N. Ieno, N. J. Walker, A. A. Saveliev, and G. M. Smith. 2009. <em>Mixed Effects Models and Extensions in Ecology with <span>R</span></em>. New York: Springer.
</div>
</div>
</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="../chapters/08-glmm.html" class="pagination-link" aria-label="Generalized linear mixed models">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Generalized linear mixed models</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="../chapters/10-penalized.html" class="pagination-link" aria-label="Penalized regression">
        <span class="nav-page-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Penalized regression</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p>statmodels7</p>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    </div>
    <div class="nav-footer-right">
      &nbsp;
    </div>
  </div>
</footer>




<script src="../site_libs/quarto-html/zenscroll-min.js"></script>
</body></html>